struct Lesson32Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "zàicì", chinese: "再次", russian: "опять/снова", english: "again"),
        Flashcard(pinyin: "qiántiān", chinese: "前天", russian: "позавчера", english: "the day before yesterday"),
        Flashcard(pinyin: "tóuyūn", chinese: "头晕", russian: "кружится голова", english: "dizzy"),
        Flashcard(pinyin: "wǒ yǒudiǎnr tóuyūn", chinese: "我有点儿头晕", russian: "у меня немного кружится голова", english: "I feel a bit dizzy"),
        Flashcard(pinyin: "wǒ méi qù", chinese: "我没去", russian: "я не пошел", english: "I didn't go"),
        Flashcard(pinyin: "diànyǐng yuàn", chinese: "电影院", russian: "кинотеатр", english: "cinema"),
        Flashcard(pinyin: "diànyǐng", chinese: "电影", russian: "фильм", english: "movie"),
        Flashcard(pinyin: "juédìng", chinese: "决定", russian: "решение", english: "decision"),
        Flashcard(pinyin: "wǒ lián xiànzài", chinese: "我连现在", russian: "даже сейчас", english: "even now"),
        Flashcard(pinyin: "chéngjiù", chinese: "成就", russian: "достижение", english: "achievement"),
        Flashcard(pinyin: "cóng kāishǐ", chinese: "从开始", russian: "с начала", english: "from the beginning"),
        Flashcard(pinyin: "biān wán", chinese: "编完", russian: "закончить писать", english: "finish writing"),
        Flashcard(pinyin: "néng mǎi dào", chinese: "能买到", russian: "купить", english: "can buy"),
        Flashcard(pinyin: "yāoqiú", chinese: "要求", russian: "требование", english: "requirement"),
        Flashcard(pinyin: "lián píngmù", chinese: "连屏幕", russian: "подключиться к экрану", english: "connect to the screen"),
        Flashcard(pinyin: "zhēngxī", chinese: "珍惜", russian: "ценить", english: "cherish"),
        Flashcard(pinyin: "guānxì", chinese: "关系", russian: "отношения", english: "relationship"),
        Flashcard(pinyin: "gěi/gen tāmen wánr", chinese: "给/跟他们玩儿", russian: "играть с ними", english: "play with them"),
        Flashcard(pinyin: "jiějué wèntí", chinese: "解决问题", russian: "решить вопрос", english: "solve the problem"),
        Flashcard(pinyin: "fúwù", chinese: "服务", russian: "сервис/услуги", english: "service"),
        Flashcard(pinyin: "wǒ néng shàngxiàn gōngzuò", chinese: "我能上网工作", russian: "работать онлайн могу", english: "I can work online"),
        Flashcard(pinyin: "cónglái bù", chinese: "从来不", russian: "никогда не делает", english: "never does"),
        Flashcard(pinyin: "cónglái méi", chinese: "从来没", russian: "никогда не делал", english: "never did"),
        Flashcard(pinyin: "xīcān", chinese: "西餐", russian: "западная кухня", english: "western food"),
        Flashcard(pinyin: "bù jīngcháng", chinese: "不经常", russian: "редко/не часто", english: "not often"),
        Flashcard(pinyin: "jiārù wǒmen yīqǐ wánr", chinese: "加入我们一起玩儿", russian: "присоединились к нам", english: "joined us to play"),
        Flashcard(pinyin: "yāoqǐng/qǐng", chinese: "邀请/请", russian: "приглашать", english: "invite"),
        Flashcard(pinyin: "jièjué", chinese: "拒绝", russian: "отказываться", english: "refuse"),
        Flashcard(pinyin: "liú zài jiā", chinese: "留在家", russian: "оставаться дома", english: "stay at home"),
        Flashcard(pinyin: "bānjiā", chinese: "搬家", russian: "переезжать", english: "move house"),
        Flashcard(pinyin: "liǎng gè yuè yǐhòu wǒ dǎsuàn bānjiā", chinese: "两个月以后我打算搬家", russian: "через два месяца я планирую переехать", english: "I plan to move in two months"),
        Flashcard(pinyin: "A lǐ B hěn yuǎn", chinese: "A离B很远", russian: "А далеко от В", english: "A is far from B"),
        Flashcard(pinyin: "wǒ lí shì zhōngxīn hěn yuǎn", chinese: "我离市中心很远", russian: "я далеко от центра города", english: "I am far from the city center"),
        Flashcard(pinyin: "gōng lǐ", chinese: "公里", russian: "км", english: "km"),
        Flashcard(pinyin: "bù gòu kànzhòng", chinese: "不够看重", russian: "недооценивать", english: "underestimate"),
        Flashcard(pinyin: "bù gòu zhùyì", chinese: "不够注意", russian: "не уделять внимания", english: "not pay enough attention"),
        Flashcard(pinyin: "shìhé de dìfāng", chinese: "适合的地方", russian: "подходящее место", english: "suitable place"),
        Flashcard(pinyin: "pútáo yá", chinese: "葡萄牙", russian: "Португалия", english: "Portugal"),
        Flashcard(pinyin: "jiā lì fú ní yà", chinese: "加利福尼亚", russian: "Калифорния", english: "California"),
        Flashcard(pinyin: "wǒ gēn rénzàozhìnéng yīqǐ biānchéng", chinese: "我跟人造智能一起编程", russian: "я программирую с ИИ", english: "I program with AI"),
        Flashcard(pinyin: "biānchéng", chinese: "编程", russian: "писать программу", english: "programming"),
        Flashcard(pinyin: "biānchéng yī wán de shíhòu", chinese: "编程一完的时候", russian: "после завершения программирования", english: "when programming is finished"),
        Flashcard(pinyin: "wǎngluò de chéngxù yuán", chinese: "网络的程序员", russian: "онлайн программист", english: "online programmer"),
        Flashcard(pinyin: "chéngxù dàimǎ", chinese: "程序代码", russian: "код программы", english: "program code"),
        Flashcard(pinyin: "zìjǐ de sīxiǎng", chinese: "自己的思想", russian: "собственные мысли", english: "own thoughts"),
        Flashcard(pinyin: "fāzhǎn", chinese: "发展", russian: "развиваться", english: "develop"),
        Flashcard(pinyin: "chéngjiù", chinese: "成就", russian: "достижение", english: "achievement"),
        Flashcard(pinyin: "méi jiàn tā", chinese: "没见她", russian: "не встречал ее", english: "didn't meet her"),
        Flashcard(pinyin: "xiāngxìn", chinese: "相信", russian: "верить", english: "believe"),
        Flashcard(pinyin: "wǒ néng shàngxiàn gōngzuò", chinese: "我能上网工作", russian: "работать онлайн могу", english: "I can work online"),
        Flashcard(pinyin: "yāoqiú", chinese: "要求", russian: "требование", english: "requirement"),
        Flashcard(pinyin: "zhèngxī", chinese: "珍惜", russian: "ценить", english: "cherish"),
        Flashcard(pinyin: "guānxì", chinese: "关系", russian: "отношения", english: "relationship"),
        Flashcard(pinyin: "zhěngtiān", chinese: "整天", russian: "целый день", english: "all day"),
        Flashcard(pinyin: "liánxì", chinese: "联系", russian: "контактировать", english: "contact"),
        Flashcard(pinyin: "fēngkuáng", chinese: "疯狂", russian: "сумасшедший", english: "crazy"),
        Flashcard(pinyin: "zhǔyì", chinese: "注意", russian: "внимание", english: "attention"),
        Flashcard(pinyin: "xīwàng", chinese: "希望", russian: "надеяться", english: "hope"),
    ]
}
