struct Lesson12Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "jiànmiàn le péngyǒu", chinese: "见面了朋友", russian: "встретил друга", english: "met a friend"),
        Flashcard(pinyin: "gēn péngyǒu jiànmiàn", chinese: "跟朋友见面", russian: "встретиться с другом", english: "meet with a friend"),
        Flashcard(pinyin: "jiàn le péngyǒu", chinese: "见了朋友", russian: "встретил друга", english: "met a friend"),
        Flashcard(pinyin: "yīnxiāng", chinese: "音箱", russian: "колонка", english: "speaker"),
        Flashcard(pinyin: "diànnǎo yóuxì", chinese: "电脑游戏", russian: "компьютерная игра", english: "computer game"),
        Flashcard(pinyin: "shàng zhōu wǒ zuò le shénme", chinese: "上周我做了什么", russian: "что я делал на прошлой неделе", english: "what did I do last week"),
        Flashcard(pinyin: "huíqù jiā", chinese: "回去家", russian: "вернуться домой", english: "go home"),
        Flashcard(pinyin: "huí jiā qù", chinese: "回家去", russian: "пойти домой", english: "go home"),
        Flashcard(pinyin: "shàng lái", chinese: "上来", russian: "к тебе", english: "come up"),
        Flashcard(pinyin: "shàng qù", chinese: "上去", russian: "от тебя", english: "go up"),
        Flashcard(pinyin: "jìn lái", chinese: "进来", russian: "заходи (ко мне)", english: "come in"),
        Flashcard(pinyin: "jìn qù", chinese: "进去", russian: "входи (от меня)", english: "go in"),
        Flashcard(pinyin: "jìn jiàoshì qù", chinese: "进教室去", russian: "войти в класс", english: "enter the classroom"),
        Flashcard(pinyin: "dài zuòyè lái", chinese: "带作业来", russian: "приносить задание", english: "bring homework"),
        Flashcard(pinyin: "dài lái zuòyè", chinese: "带来作业", russian: "приносить задание", english: "bring homework"),
        Flashcard(pinyin: "tā dǎsuàn le huíguó", chinese: "他打算了回国", russian: "он планировал вернуться на родину", english: "he planned to return to his country"),
        Flashcard(pinyin: "ānpái", chinese: "安排", russian: "организовать", english: "arrange"),
        Flashcard(pinyin: "yáncháng", chinese: "延长", russian: "продолжать", english: "extend"),
        Flashcard(pinyin: "tā kuài huí jiā le", chinese: "他快回家了", russian: "он скоро будет дома", english: "he will be home soon"),
        Flashcard(pinyin: "kuài yào ... le", chinese: "快要...了", russian: "вот вот.. (скоро)", english: "about to..."),
        Flashcard(pinyin: "wǒmen hěn shǎo jiànmiàn", chinese: "我们很少见面", russian: "мы редко видимся", english: "we rarely meet"),
        Flashcard(pinyin: "bāng wǒ qīngsōng yīxià", chinese: "帮我轻松一下", russian: "помоги мне расслабиться", english: "help me relax"),
        Flashcard(pinyin: "bālěiwǔ", chinese: "芭蕾舞", russian: "балет", english: "ballet"),
        Flashcard(pinyin: "Mòsīkē", chinese: "莫斯科", russian: "Москва", english: "Moscow"),
        Flashcard(pinyin: "zài Mòsīkē de bālěiwǔ", chinese: "在莫斯科的芭蕾舞", russian: "балет в Москве", english: "ballet in Moscow"),
        Flashcard(pinyin: "yǎnchū", chinese: "演出", russian: "выступать", english: "perform"),
        Flashcard(pinyin: "biǎoyǎn", chinese: "表演", russian: "выступление", english: "performance"),
        Flashcard(pinyin: "zuì zāogāo de", chinese: "最糟糕的", russian: "самый худший", english: "the worst"),
        Flashcard(pinyin: "zhōngděng", chinese: "中等", russian: "средний", english: "average"),
        Flashcard(pinyin: "Duānwǔ Jié", chinese: "端午节", russian: "фестиваль драконьих лодок", english: "Dragon Boat Festival"),
        Flashcard(pinyin: "jiàrì", chinese: "假日", russian: "выходные", english: "holiday"),
        Flashcard(pinyin: "jiérì", chinese: "节日", russian: "праздник", english: "festival"),
        Flashcard(pinyin: "wǒ bù zhīdào jiérì huì zuò shénme", chinese: "我不知道节日会做什么", russian: "я не знаю что буду делать на празднике", english: "I don't know what to do on the festival"),
        Flashcard(pinyin: "fù liǎng bèi de jiàgé", chinese: "付两倍的价格", russian: "платить вдвое больше", english: "pay twice the price"),
        Flashcard(pinyin: "rènào", chinese: "热闹", russian: "шумно, людно", english: "lively"),
        Flashcard(pinyin: "wǒ gèng hǎo liú zài jiā", chinese: "我更好留在家", russian: "лучше остаться дома", english: "better stay at home"),
        Flashcard(pinyin: "jíshǐ...yě...", chinese: "即使...也...", russian: "даже если... я все равно...", english: "even if... still..."),
        Flashcard(pinyin: "zūfáng", chinese: "租房", russian: "снимать жилье", english: "rent a house"),
        Flashcard(pinyin: "liǎng gè yuè qián", chinese: "两个月前", russian: "два месяца назад", english: "two months ago"),
        Flashcard(pinyin: "hěn yǒuqián rén", chinese: "很有钱人", russian: "богатый человек", english: "rich person"),
        Flashcard(pinyin: "fùyù de rén", chinese: "富裕的人", russian: "богатый человек", english: "wealthy person"),
        Flashcard(pinyin: "Hǎilì Bōtè", chinese: "哈利波特", russian: "Гарри Поттер", english: "Harry Potter"),
        Flashcard(pinyin: "duì...xíguàn", chinese: "对...习惯", russian: "привыкнуть к чему-то", english: "get used to something"),
        Flashcard(pinyin: "zhùyì", chinese: "注意", russian: "следить за", english: "pay attention to"),
        Flashcard(pinyin: "fāngshì", chinese: "方式", russian: "метод", english: "method"),
        Flashcard(pinyin: "fāngfǎ", chinese: "方法", russian: "метод", english: "method"),
        Flashcard(pinyin: "wǒ jiāo de fāngfǎ", chinese: "我教的方法", russian: "мой метод", english: "my method"),
        Flashcard(pinyin: "jiàoyù shuǐpíng", chinese: "教育水平", russian: "уровень образования", english: "education level"),
        Flashcard(pinyin: "zūnshǒu", chinese: "遵守", russian: "следовать чему-то", english: "follow"),
        Flashcard(pinyin: "huàr", chinese: "画儿", russian: "картина", english: "painting"),
        Flashcard(pinyin: "yǒumíng shēngyìrén de huàr", chinese: "有名生意人的画儿", russian: "картина известного бизнесмена", english: "famous businessman's painting"),
        Flashcard(pinyin: "érqiě", chinese: "而且", russian: "к тому же", english: "moreover"),
        Flashcard(pinyin: "mùbiāo", chinese: "目标", russian: "цель", english: "goal"),
        Flashcard(pinyin: "mùdì", chinese: "目的", russian: "цель", english: "purpose")
    ]
}
