struct Lesson22Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "yǒumíng", chinese: "有名", russian: "известный", english: "famous"),
        Flashcard(pinyin: "nà jiā cāntīng", chinese: "那家餐厅", russian: "тот ресторан", english: "that restaurant"),
        Flashcard(pinyin: "chēng", chinese: "称", russian: "зовут/называется", english: "called"),
        Flashcard(pinyin: "wǒmen jiànle zài zhèr", chinese: "我们见了在这儿", russian: "мы встретились здесь", english: "we met here"),
        Flashcard(pinyin: "cāntīng zài wǒ jiā pángbiān", chinese: "餐厅在我家旁边", russian: "ресторан рядом с моим домом", english: "the restaurant is next to my house"),
        Flashcard(pinyin: "ānpái/dǎsuàn", chinese: "安排/打算", russian: "планировать", english: "plan"),
        Flashcard(pinyin: "jiéshù wánr", chinese: "结束玩儿", russian: "заканчивать веселиться", english: "finish having fun"),
        Flashcard(pinyin: "jiéshù", chinese: "结束", russian: "заканчивать", english: "finish"),
        Flashcard(pinyin: "nǚxìng péngyou", chinese: "女性朋友", russian: "подруга (не девушка)", english: "female friend (not girlfriend)"),
        Flashcard(pinyin: "liú zài", chinese: "留在", russian: "оставаться", english: "stay"),
        Flashcard(pinyin: "yāoqǐng/qǐng", chinese: "邀请/请", russian: "приглашать", english: "invite"),
        Flashcard(pinyin: "wǒmen tóngyìle jiàn zài jiǔbā pángbiān", chinese: "我们同意了见在酒吧旁边", russian: "мы договорились встретиться рядом с баром", english: "we agreed to meet next to the bar"),
        Flashcard(pinyin: "jīngyàn", chinese: "经验", russian: "опыт", english: "experience"),
        Flashcard(pinyin: "gēnzōng", chinese: "跟踪", russian: "преследовать", english: "follow"),
        Flashcard(pinyin: "tā de shēnghuó gēn pǔtōng de rén bù tóng", chinese: "他的生活跟普通的人不同", russian: "его жизнь отличается от обычной", english: "his life is different from ordinary people"),
        Flashcard(pinyin: "wǒ yào gōngzuò duō yīdiǎnr", chinese: "我要工作多一点儿", russian: "мне нужно больше работать", english: "I need to work more"),
        Flashcard(pinyin: "méi chénggōng", chinese: "没成功", russian: "не добиться успеха", english: "not succeed"),
        Flashcard(pinyin: "shībài", chinese: "失败", russian: "проваливаться (неудача)", english: "fail"),
        Flashcard(pinyin: "shuō huǎng", chinese: "说谎", russian: "говорить неправду/лгать", english: "lie"),
        Flashcard(pinyin: "shuō mǔyǔ de rén", chinese: "说母语的人", russian: "человек разговаривающий на родном языке", english: "native language speaker"),
        Flashcard(pinyin: "fāshēng", chinese: "发生", russian: "происходить", english: "happen"),
        Flashcard(pinyin: "zhuāzhù", chinese: "抓住", russian: "ловить/схватывать", english: "catch"),
        Flashcard(pinyin: "wēixiǎn", chinese: "危险", russian: "опасный", english: "dangerous"),
        Flashcard(pinyin: "jiātíng", chinese: "家庭", russian: "семья", english: "family"),
        Flashcard(pinyin: "jùjué", chinese: "拒绝", russian: "отказываться", english: "refuse"),
        Flashcard(pinyin: "jiějué", chinese: "解决", russian: "решать (проблемы)", english: "solve (problems)"),
        Flashcard(pinyin: "jiǎnlì", chinese: "简历", russian: "резюме", english: "resume"),
        Flashcard(pinyin: "yuányīn", chinese: "原因", russian: "причина", english: "reason"),
        Flashcard(pinyin: "xià yī bù", chinese: "下一步", russian: "следующий шаг", english: "next step"),
        Flashcard(pinyin: "jíshǐ", chinese: "即使", russian: "даже если", english: "even if"),
        Flashcard(pinyin: "bàn nián (hé bàn ge nián)", chinese: "半年", russian: "полгода", english: "half year"),
        Flashcard(pinyin: "fùmǔ", chinese: "父母", russian: "родители", english: "parents"),
        Flashcard(pinyin: "shìqíng", chinese: "事情", russian: "дело", english: "matter"),
        Flashcard(pinyin: "Guóqìng Jié", chinese: "国庆节", russian: "национальный праздник", english: "National Day"),
        Flashcard(pinyin: "fàngjià", chinese: "放假", russian: "отпуск", english: "holiday"),
        Flashcard(pinyin: "zhàngpéng", chinese: "帐篷", russian: "палатка", english: "tent"),
        Flashcard(pinyin: "qùnián", chinese: "去年", russian: "прошлый год", english: "last year"),
        Flashcard(pinyin: "míngnián", chinese: "明年", russian: "следующий год", english: "next year"),
        Flashcard(pinyin: "hú", chinese: "湖", russian: "озеро", english: "lake")
    ]
}
