struct Lesson9Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Shēnyīn", chinese: "声音", russian: "Звук", english: "Sound"),
        Flashcard(pinyin: "Chāo", chinese: "吵", russian: "Шумный", english: "Noisy"),
        Flashcard(pinyin: "Shàngkè", chinese: "上课", russian: "Занятие", english: "Class"),
        Flashcard(pinyin: "Yěcān", chinese: "野餐", russian: "Пикник", english: "Picnic"),
        Flashcard(pinyin: "Pàiduì", chinese: "派对", russian: "Вечеринка", english: "Party"),
        Flashcard(pinyin: "Cānjiā", chinese: "参加", russian: "Присутствовать", english: "Attend"),
        Flashcard(pinyin: "Gēn", chinese: "跟", russian: "С (кем-то)", english: "With (someone)"),
        Flashcard(pinyin: "Gěi", chinese: "给", russian: "Для (кого-то)", english: "For (someone)"),
        Flashcard(pinyin: "Zhídào wǎnshàng 5 diǎn", chinese: "直到晚上5点", russian: "До 5 вечера", english: "Until 5 PM"),
        Flashcard(pinyin: "Kāishǐ", chinese: "开始", russian: "Начинать", english: "Start"),
        Flashcard(pinyin: "Jiéshù", chinese: "结束", russian: "Заканчивать", english: "Finish"),
        Flashcard(pinyin: "Qǔxiāo", chinese: "取消", russian: "Отменять", english: "Cancel"),
        Flashcard(pinyin: "Huódòng", chinese: "活动", russian: "Мероприятие", english: "Event"),
        Flashcard(pinyin: "Gǎnrǎn", chinese: "感染", russian: "Заразиться", english: "Infect"),
        Flashcard(pinyin: "Hěn jiànkāng", chinese: "很健康", russian: "Очень здоровый", english: "Very healthy"),
        Flashcard(pinyin: "Dòng xué", chinese: "洞穴", russian: "Пещера (общий термин)", english: "Cave (general term)"),
        Flashcard(pinyin: "Shān dòng", chinese: "山洞", russian: "Горная пещера", english: "Mountain cave"),
        Flashcard(pinyin: "Fēngjǐng", chinese: "风景", russian: "Пейзаж", english: "Scenery"),
        Flashcard(pinyin: "Měilì", chinese: "美丽", russian: "Красота / красивый", english: "Beautiful"),
        Flashcard(pinyin: "Wǒ bù gēn wǒ de péngyǒu wánr hěn duō", chinese: "我不跟我的朋友玩儿很多", russian: "Я не играю с друзьями много", english: "I don't play with my friends much"),
        Flashcard(pinyin: "Yǒuyì", chinese: "友谊", russian: "Дружба", english: "Friendship"),
        Flashcard(pinyin: "Guānxì", chinese: "关系", russian: "Отношения", english: "Relationship"),
        Flashcard(pinyin: "Duì nǐ lái shuō", chinese: "对你来说", russian: "Говоря о тебе", english: "For you"),
        Flashcard(pinyin: "Duì nǐ lái shuō, yǒuyì hěn zhòngyào ma?", chinese: "对你来说，友谊很重要吗?", russian: "Для тебя дружба важна?", english: "Is friendship important to you?"),
        Flashcard(pinyin: "Hěnduō", chinese: "很多", russian: "Много", english: "A lot"),
        Flashcard(pinyin: "Gèng duō", chinese: "更多", russian: "Больше", english: "More"),
        Flashcard(pinyin: "Zuì duō", chinese: "最多", russian: "Максимум", english: "Most"),
        Flashcard(pinyin: "Wán měi", chinese: "完美", russian: "Идеальный", english: "Perfect"),
        Flashcard(pinyin: "Wánr gēn bù wánměi de rén", chinese: "玩儿跟不完美的人", russian: "Играть с несовершенными людьми", english: "Play with imperfect people"),
        Flashcard(pinyin: "Jiànmiàn", chinese: "见面", russian: "Встретиться", english: "Meet"),
        Flashcard(pinyin: "Jiàn le nǐ de miàn", chinese: "见了你的面", russian: "Встретился с тобой", english: "Met with you"),
        Flashcard(pinyin: "Jiàn le 3 cì miàn", chinese: "见了三次面", russian: "Встретился три раза", english: "Met three times"),
        Flashcard(pinyin: "Que dìng", chinese: "确定", russian: "Точно / Уверен", english: "Sure"),
        Flashcard(pinyin: "Cúnzài", chinese: "存在", russian: "Существовать", english: "Exist"),
        Flashcard(pinyin: "Jiēshòu", chinese: "接受", russian: "Принять", english: "Accept"),
        Flashcard(pinyin: "Cháng shì", chinese: "尝试", russian: "Пробовать / пытаться", english: "Try"),
        Flashcard(pinyin: "Huīfù", chinese: "恢复", russian: "Выздороветь", english: "Recover"),
        Flashcard(pinyin: "Nénglì", chinese: "能力", russian: "Способность", english: "Ability"),
        Flashcard(pinyin: "Jìnéng", chinese: "技能", russian: "Навык", english: "Skill"),
        Flashcard(pinyin: "Huà tí", chinese: "话题", russian: "Тема (разговора)", english: "Topic (conversation)"),
        Flashcard(pinyin: "Tí mù", chinese: "题目", russian: "Тема (задания)", english: "Topic (task)"),
        Flashcard(pinyin: "Jiànféi", chinese: "减肥", russian: "Похудение", english: "Lose weight"),
        Flashcard(pinyin: "Jiǎn le 4 gōngjīn", chinese: "减了4公斤", russian: "Похудел на 4 кг", english: "Lost 4 kg"),
        Flashcard(pinyin: "Tóngshí", chinese: "同时", russian: "В то же время", english: "At the same time"),
        Flashcard(pinyin: "Fāngshì", chinese: "方式", russian: "Метод / способ", english: "Method"),
        Flashcard(pinyin: "Dú shū le", chinese: "读书了", russian: "Прочитал книгу", english: "Read a book"),
        Flashcard(pinyin: "Kàn shū le", chinese: "看书了", russian: "Читал книгу", english: "Reading a book"),
        Flashcard(pinyin: "Kàn wán shū le", chinese: "看完书了", russian: "Прочитал книгу до конца", english: "Finished reading a book"),
        Flashcard(pinyin: "Guānyú", chinese: "关于", russian: "О (чем-то)", english: "About"),
        Flashcard(pinyin: "Shìjiè", chinese: "世界", russian: "Мир / свет", english: "World"),
        Flashcard(pinyin: "Liúxíng", chinese: "流行", russian: "Популярный", english: "Popular"),
        Flashcard(pinyin: "Rén gōng zhì néng", chinese: "人工智能", russian: "Искусственный интеллект", english: "Artificial intelligence"),
        Flashcard(pinyin: "Wǎng luò", chinese: "网络", russian: "Сеть", english: "Network"),
        Flashcard(pinyin: "Shíjiān", chinese: "时间", russian: "Время", english: "Time"),
        Flashcard(pinyin: "Bù làngfèi shíjiān", chinese: "不浪费时间", russian: "Не тратить время впустую", english: "Don't waste time")
    ]
}
