struct Lesson11Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Chéngyì", chinese: "成意", russian: "Умножить", english: "Multiply"),
        Flashcard(pinyin: "Wèilái", chinese: "未来", russian: "Будущее", english: "Future"),
        Flashcard(pinyin: "Dà mùdì", chinese: "大目的", russian: "Ставить цель", english: "Set a goal"),
        Flashcard(pinyin: "Gèng duō lìqì", chinese: "更多力气", russian: "Больше сил", english: "More strength"),
        Flashcard(pinyin: "Néng zuò bǐ xiànzài gèng duō dōngxī", chinese: "能做比现在更多东西", russian: "Добиваться больше", english: "Achieve more"),
        Flashcard(pinyin: "Dǎdào", chinese: "达到", russian: "Достигать", english: "To reach"),
        Flashcard(pinyin: "Wùlǐ", chinese: "物理", russian: "Физика", english: "Physics"),
        Flashcard(pinyin: "Làngfèi shíjiān", chinese: "浪费时间", russian: "Тратить время впустую", english: "Waste time"),
        Flashcard(pinyin: "Zài cì", chinese: "再次", russian: "Еще раз", english: "Once more"),
        Flashcard(pinyin: "Xīn wén", chinese: "新闻", russian: "Новости", english: "News"),
        Flashcard(pinyin: "Qī shí yī", chinese: "七十一", russian: "Семьдесят один", english: "Seventy-one"),
        Flashcard(pinyin: "Zhè yě shì wǒ de mùdì", chinese: "这也是我的目的", russian: "Это тоже моя цель", english: "This is also my goal"),
        Flashcard(pinyin: "Sì yì měiyuán", chinese: "四亿美元", russian: "Четыреста миллионов долларов", english: "Four hundred million dollars"),
        Flashcard(pinyin: "Sìshí yì měiyuán", chinese: "四十亿美元", russian: "Четыре миллиарда долларов", english: "Four billion dollars"),
        Flashcard(pinyin: "Jiādà shí cì", chinese: "加大十次", russian: "Увеличить в десять раз", english: "Increase tenfold"),
        Flashcard(pinyin: "Shēng yī shū", chinese: "声一书", russian: "Аудиокнига", english: "Audiobook"),
        Flashcard(pinyin: "Zhǎng dà", chinese: "长大", russian: "Стать большим", english: "Grow up"),
        Flashcard(pinyin: "Chū jìng", chinese: "出境", russian: "Выезжать за границу", english: "Go abroad"),
        Flashcard(pinyin: "Bù shǔo huā", chinese: "不说话", russian: "Молчать", english: "Keep silent"),
        Flashcard(pinyin: "Bù shuō huà hěn duō", chinese: "不说话很多", russian: "Молчать много", english: "Keep very silent"),
        Flashcard(pinyin: "Yǐngxiǎng wǒ", chinese: "影响我", russian: "Повлиять на меня", english: "Influence me"),
        Flashcard(pinyin: "Dùi wǒ yǒu hěn dà de yǐngxiǎng", chinese: "对我有很大的影响", russian: "Оказать на меня большое влияние", english: "Have a big influence on me"),
        Flashcard(pinyin: "Néng kòngzhì zìjǐ de sīwéi", chinese: "能控制自己的思维", russian: "Контролировать свои мысли", english: "Control one's thoughts"),
        Flashcard(pinyin: "Qǔzhù zài bālí dǎo", chinese: "驻足在巴黎岛", russian: "Остановиться на острове Бали", english: "Stay on Bali island"),
        Flashcard(pinyin: "Kòngzhì", chinese: "控制", russian: "Контролировать", english: "Control"),
        Flashcard(pinyin: "Guānxi", chinese: "关系", russian: "Отношения", english: "Relationship"),
        Flashcard(pinyin: "Chūjìng chū wūkèlán de jìng", chinese: "出境出乌克兰的境", russian: "Выехать за пределы Украины", english: "Exit the territory of Ukraine"),
        Flashcard(pinyin: "Wǒmen zhīdào néng zuò shénme dōngxī", chinese: "我们知道能做什么东西", russian: "Мы знаем, что можем делать", english: "We know what we can do"),
        Flashcard(pinyin: "Zuì yǒuxiào de bànfǎ", chinese: "最有效的办法", russian: "Самый эффективный способ", english: "The most effective method"),
        Flashcard(pinyin: "Bùfen", chinese: "部分", russian: "Часть", english: "Part"),
        Flashcard(pinyin: "Wǒ mùdì de yī bùfen", chinese: "我的目的的一部分", russian: "Часть моей цели", english: "Part of my goal"),
        Flashcard(pinyin: "Dà de dǎo", chinese: "大得到", russian: "Получить много", english: "Get a lot"),
        Flashcard(pinyin: "Dà bù dǎo", chinese: "大不到", russian: "Не получить много", english: "Not get much"),
        Flashcard(pinyin: "Kàn de dǎo", chinese: "看得到", russian: "Могу увидеть", english: "Can see"),
        Flashcard(pinyin: "Kàn bù dǎo", chinese: "看不到", russian: "Не могу увидеть", english: "Cannot see"),
        Flashcard(pinyin: "Qīnmì", chinese: "亲密", russian: "Близкий", english: "Close"),
        Flashcard(pinyin: "Diu shī sù dù", chinese: "丢失速度", russian: "Терять скорость", english: "Lose speed"),
        Flashcard(pinyin: "Diu shī", chinese: "丢失", russian: "Потерять", english: "Lose"),
        Flashcard(pinyin: "Zhǐ shǎo", chinese: "至少", russian: "Как минимум", english: "At least"),
        Flashcard(pinyin: "Zhīchí", chinese: "支持", russian: "Поддерживать", english: "Support"),
        Flashcard(pinyin: "Zhè shì yǒuyòng", chinese: "这是有用", russian: "Это полезно", english: "This is useful"),
        Flashcard(pinyin: "Zhè shì hěn yǒuyòng de", chinese: "这是很有用的", russian: "Это очень полезно", english: "This is very useful"),
        Flashcard(pinyin: "Pínghéng", chinese: "平衡", russian: "Баланс", english: "Balance"),
        Flashcard(pinyin: "Jī huì", chinese: "机会", russian: "Возможность", english: "Opportunity")
    ]
}
