struct Lesson19Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "rì", chinese: "日", russian: "число", english: "day/date"),
        Flashcard(pinyin: "hào", chinese: "号", russian: "число", english: "number"),
        Flashcard(pinyin: "tiān", chinese: "天", russian: "дней", english: "days"),
        Flashcard(pinyin: "dānwù", chinese: "耽误", russian: "задерживать/откладывать", english: "delay"),
        Flashcard(pinyin: "cáiwù jīnglǐ", chinese: "财务经理", russian: "финансовый менеджер", english: "financial manager"),
        Flashcard(pinyin: "jiéshù", chinese: "结束", russian: "закончить", english: "end/finish"),
        Flashcard(pinyin: "zhè yī cì", chinese: "这一次", russian: "этот раз", english: "this time"),
        Flashcard(pinyin: "yālì", chinese: "压力", russian: "стресс", english: "stress"),
        Flashcard(pinyin: "qíngkuàng", chinese: "情况", russian: "ситуация", english: "situation"),
        Flashcard(pinyin: "gèng shǎo fàn", chinese: "更少饭", russian: "меньше еды", english: "less food"),
        Flashcard(pinyin: "jiǎn 2 gōngjīn", chinese: "减2公斤", russian: "похудеть на 2 кг", english: "lose 2 kg"),
        Flashcard(pinyin: "wǒ kěyǐ chī yǐqián fàn liàng de 70%", chinese: "我可以吃以前饭量的70%", russian: "я могу есть 70% от прежнего объема пищи", english: "I can eat 70% of my previous food intake"),
        Flashcard(pinyin: "liú", chinese: "留", russian: "оставаться", english: "stay"),
        Flashcard(pinyin: "zhēnxī", chinese: "珍惜", russian: "ценить", english: "cherish"),
        Flashcard(pinyin: "jiànmiàn", chinese: "见面", russian: "встретиться", english: "meet"),
        Flashcard(pinyin: "gǎi cuòwù", chinese: "改错误", russian: "исправлять ошибку", english: "correct mistake"),
        Flashcard(pinyin: "tǎolùn huàtí", chinese: "讨论话题", russian: "обсуждать тему", english: "discuss topic"),
        Flashcard(pinyin: "fēnshǒu", chinese: "分手", russian: "расставаться", english: "break up"),
        Flashcard(pinyin: "cānjù", chinese: "餐具", russian: "столовые приборы", english: "tableware"),
        Flashcard(pinyin: "yīngyǔ wéi mǔyǔ", chinese: "英语为母语", russian: "английский как родной язык", english: "native English speaker"),
        Flashcard(pinyin: "ài'ěrlán", chinese: "爱尔兰", russian: "ирландия", english: "Ireland"),
        Flashcard(pinyin: "āgēntíng", chinese: "阿根廷", russian: "аргентина", english: "Argentina"),
        Flashcard(pinyin: "quánjī", chinese: "拳击", russian: "бокс", english: "boxing"),
        Flashcard(pinyin: "sàichē", chinese: "赛车", russian: "гонки (соревнования)", english: "car racing"),
        Flashcard(pinyin: "yǐqián", chinese: "以前", russian: "предыдущий", english: "previous"),
        Flashcard(pinyin: "lìshǐ zhōngxīn yǒudiǎn er yuǎn", chinese: "历史中心有点儿远", russian: "от центра немного далеко", english: "a bit far from the city center"),
        Flashcard(pinyin: "zhǎng de", chinese: "长得", russian: "выглядеть", english: "look like"),
        Flashcard(pinyin: "bǐ yǐqián de fángzi hǎo", chinese: "比以前的房子好", russian: "лучше, чем предыдущий дом", english: "better than the previous house"),
        Flashcard(pinyin: "dǎsǎo", chinese: "打扫", russian: "убирать", english: "clean"),
        Flashcard(pinyin: "shōushí dōngxi", chinese: "收拾东西", russian: "убирать/паковать/укладывать", english: "tidy up/pack"),
        Flashcard(pinyin: "tàofáng", chinese: "套房", russian: "квартира", english: "apartment"),
        Flashcard(pinyin: "shòuyī", chinese: "兽医", russian: "ветеринар", english: "veterinarian"),
        Flashcard(pinyin: "fēixíngyuán", chinese: "飞行员", russian: "пилот", english: "pilot"),
        Flashcard(pinyin: "qīngjiégōng", chinese: "清洁工", russian: "уборщица", english: "cleaner"),
        Flashcard(pinyin: "shèyǐngshī", chinese: "摄影师", russian: "фотограф", english: "photographer"),
        Flashcard(pinyin: "chéngrén", chinese: "成人", russian: "взрослый", english: "adult"),
        Flashcard(pinyin: "shūcài", chinese: "蔬菜", russian: "овощи", english: "vegetables"),
        Flashcard(pinyin: "bōcài", chinese: "菠菜", russian: "шпинат", english: "spinach"),
        Flashcard(pinyin: "báicài", chinese: "白菜", russian: "капуста", english: "cabbage"),
        Flashcard(pinyin: "huācài", chinese: "花菜", russian: "цветная капуста", english: "cauliflower"),
        Flashcard(pinyin: "xīlánhuā", chinese: "西兰花", russian: "брокколи", english: "broccoli"),
        Flashcard(pinyin: "báiluóbo", chinese: "白萝卜", russian: "редис", english: "radish"),
        Flashcard(pinyin: "qiézi", chinese: "茄子", russian: "баклажан", english: "eggplant"),
        Flashcard(pinyin: "yùmǐ", chinese: "玉米", russian: "кукуруза", english: "corn"),
        Flashcard(pinyin: "bàomǐhuā", chinese: "爆米花", russian: "попкорн", english: "popcorn"),
        Flashcard(pinyin: "dàcōng/yángcōng", chinese: "大葱/洋葱", russian: "лук", english: "onion"),
        Flashcard(pinyin: "dàsuan", chinese: "大蒜", russian: "чеснок", english: "garlic"),
        Flashcard(pinyin: "cóngtóu", chinese: "从头", russian: "начать с начала", english: "start from scratch"),
        Flashcard(pinyin: "cóngtóu", chinese: "从头", russian: "репчатый лук", english: "onion"),
        Flashcard(pinyin: "lìzhī", chinese: "荔枝", russian: "личи", english: "lychee"),
        Flashcard(pinyin: "nánguā", chinese: "南瓜", russian: "тыква", english: "pumpkin"),
        Flashcard(pinyin: "huǒlóngguǒ", chinese: "火龙果", russian: "драгонфрукт", english: "dragon fruit"),
        Flashcard(pinyin: "bǎixiāngguǒ", chinese: "百香果", russian: "маракуйя", english: "passion fruit"),
        Flashcard(pinyin: "wǒ xiànzài bǐ yǐqián xué hànyǔ shǎo yīdiǎnr", chinese: "我现在比以前学汉语少一点儿", russian: "я сейчас учу китайский меньше, чем раньше", english: "I am studying Chinese less than before"),
        Flashcard(pinyin: "diànshìjù", chinese: "电视剧", russian: "сериалы", english: "TV series"),
        Flashcard(pinyin: "xiāoshòu jīnglǐ", chinese: "销售经理", russian: "менеджер по продажам", english: "sales manager")
    ]
}
