struct Lesson23Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "rù jìng", chinese: "入境", russian: "въезд", english: "entry"),
        Flashcard(pinyin: "shōudào/huòdé lǜkǎ", chinese: "收到/获得绿卡", russian: "получить грин карту", english: "receive/obtain green card"),
        Flashcard(pinyin: "jiànyì", chinese: "建议", russian: "совет", english: "advice"),
        Flashcard(pinyin: "tàidù", chinese: "态度", russian: "отношение", english: "attitude"),
        Flashcard(pinyin: "xīfāng rén", chinese: "西方人", russian: "западный человек", english: "westerner"),
        Flashcard(pinyin: "dàoqī", chinese: "到期", russian: "истекать", english: "expire"),
        Flashcard(pinyin: "nànmín", chinese: "难民", russian: "беженец", english: "refugee"),
        Flashcard(pinyin: "xiàjiàng", chinese: "下降", russian: "понижаться", english: "decrease"),
        Flashcard(pinyin: "huílái", chinese: "回来", russian: "возвращаться", english: "return"),
        Flashcard(pinyin: "fāngmiàn", chinese: "方面", russian: "сторона", english: "aspect"),
        Flashcard(pinyin: "wénjiàn", chinese: "文件", russian: "документы", english: "documents"),
        Flashcard(pinyin: "biéde xiǎngfǎ", chinese: "别的想法", russian: "другие мысли", english: "other thoughts"),
        Flashcard(pinyin: "biéde sīxiǎng", chinese: "别的思想", russian: "другое мышление", english: "different thinking"),
        Flashcard(pinyin: "niǔyuē", chinese: "纽约", russian: "нью йорк", english: "New York"),
        Flashcard(pinyin: "mòxīgē", chinese: "墨西哥", russian: "мексика", english: "Mexico"),
        Flashcard(pinyin: "mòsīkē", chinese: "莫斯科", russian: "москва", english: "Moscow"),
        Flashcard(pinyin: "chuānjìng", chinese: "穿境", russian: "пересекать границу", english: "cross the border"),
        Flashcard(pinyin: "shěngqián", chinese: "省钱", russian: "сохранить деньги", english: "save money"),
        Flashcard(pinyin: "jīngcháng guòlái", chinese: "经常过来", russian: "часто приходит", english: "often comes"),
        Flashcard(pinyin: "duǒcáng", chinese: "躲藏", russian: "прятаться", english: "hide"),
        Flashcard(pinyin: "shòushāng", chinese: "受伤", russian: "пострадать", english: "injured"),
        Flashcard(pinyin: "xīgài", chinese: "膝盖", russian: "колени", english: "knees"),
        Flashcard(pinyin: "wēixiǎn", chinese: "危险", russian: "опасный", english: "dangerous"),
        Flashcard(pinyin: "zhuā zhù", chinese: "抓住", russian: "ловить", english: "catch"),
        Flashcard(pinyin: "shìqū", chinese: "市区", russian: "городской район", english: "urban area"),
        Flashcard(pinyin: "kòngzhì", chinese: "控制", russian: "контролировать", english: "control"),
        Flashcard(pinyin: "duì...mǎnyì", chinese: "对...满意", russian: "быть удовлетворенным", english: "satisfied with"),
        Flashcard(pinyin: "zuòjiā", chinese: "作家", russian: "писатель", english: "writer"),
        Flashcard(pinyin: "píngshí", chinese: "平时", russian: "обычно", english: "usually"),
        Flashcard(pinyin: "měi jǐ gè yuè wǒ dōu kàn shū", chinese: "每几个我都看书", russian: "я читаю каждый месяц", english: "I read every month"),
        Flashcard(pinyin: "zhuànjì", chinese: "传记", russian: "биография", english: "biography"),
        Flashcard(pinyin: "xìnggé", chinese: "性格", russian: "характер", english: "character"),
        Flashcard(pinyin: "jīngcháng mà tā", chinese: "经常骂他", russian: "часто оскорблял его", english: "often insulted him"),
        Flashcard(pinyin: "fēi guò qù", chinese: "飞过去", russian: "улететь", english: "fly away"),
        Flashcard(pinyin: "sīxiǎng fāngshì", chinese: "思想方式", russian: "метод мышления", english: "way of thinking"),
        Flashcard(pinyin: "kēxué", chinese: "科学", russian: "наука", english: "science"),
        Flashcard(pinyin: "wèilái de shū", chinese: "未来的书", russian: "книги о будущем", english: "books about the future"),
        Flashcard(pinyin: "shìjiè", chinese: "世界", russian: "мир", english: "world"),
        Flashcard(pinyin: "yǒuqián rén", chinese: "有钱人", russian: "богатый человек", english: "rich person"),
        Flashcard(pinyin: "shìbīng", chinese: "士兵", russian: "солдат", english: "soldier"),
        Flashcard(pinyin: "hēikè", chinese: "黑客", russian: "хакер", english: "hacker"),
        Flashcard(pinyin: "sàibō pèngkè", chinese: "赛博朋克", russian: "киберпанк", english: "cyberpunk"),
        Flashcard(pinyin: "fēifǎ", chinese: "非法", russian: "нелегальный", english: "illegal"),
        Flashcard(pinyin: "nénglì", chinese: "能力", russian: "способности", english: "abilities"),
        Flashcard(pinyin: "zìyóu", chinese: "自由", russian: "свобода", english: "freedom"),
        Flashcard(pinyin: "chuàngzào", chinese: "创造", russian: "творить", english: "create"),
        Flashcard(pinyin: "yǐngxiǎng", chinese: "影响", russian: "влияние/влиять", english: "influence"),
        Flashcard(pinyin: "dāngbīng", chinese: "当兵", russian: "поступать на военную службу", english: "join the army"),
        Flashcard(pinyin: "kànfǎ", chinese: "看法", russian: "точка зрения/мнение", english: "point of view"),
        Flashcard(pinyin: "xiǎngfǎ", chinese: "想法", russian: "мысли/идеи", english: "thoughts/ideas"),
    ]
}
