struct Lesson24Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "biǎo", chinese: "表", russian: "таблица", english: "form/table"),
        Flashcard(pinyin: "lǎoshī", chinese: "老师", russian: "учитель", english: "teacher"),
        Flashcard(pinyin: "lián...yě...", chinese: "连...也...", russian: "даже", english: "even..."),
        Flashcard(pinyin: "xiǎng qǐ lái", chinese: "想起来", russian: "вспоминать", english: "remember"),
        Flashcard(pinyin: "wùlǐ", chinese: "物理", russian: "физика", english: "physics"),
        Flashcard(pinyin: "jīngyàn", chinese: "经验", russian: "опыт", english: "experience"),
        Flashcard(pinyin: "biānchéng shī", chinese: "编程师", russian: "программист", english: "programmer"),
        Flashcard(pinyin: "chéngxù yuán", chinese: "程序员", russian: "программист", english: "programmer"),
        Flashcard(pinyin: "liàngzǐ wùlǐ", chinese: "量子物理", russian: "квантовая физика", english: "quantum physics"),
        Flashcard(pinyin: "jīběn", chinese: "基本", russian: "базовый", english: "basic"),
        Flashcard(pinyin: "zhuānyè", chinese: "专业", russian: "профессия", english: "profession"),
        Flashcard(pinyin: "zhīshì", chinese: "知识", russian: "знания", english: "knowledge"),
        Flashcard(pinyin: "kànfǎ", chinese: "看法", russian: "точка зрения/мнение", english: "point of view"),
        Flashcard(pinyin: "jīngcháng guānyú shìjiè wèntí", chinese: "经常关于世界问题", russian: "часто о мировых проблемах", english: "often about world issues"),
        Flashcard(pinyin: "jiěshì", chinese: "解释", russian: "объяснение", english: "explanation"),
        Flashcard(pinyin: "xīnlǐ xué", chinese: "心理学", russian: "психология", english: "psychology"),
        Flashcard(pinyin: "gǎnqíng", chinese: "感情", russian: "эмоция", english: "emotion"),
        Flashcard(pinyin: "qíngxù", chinese: "情绪", russian: "эмоция", english: "emotion"),
        Flashcard(pinyin: "qīnqī", chinese: "亲戚", russian: "родственник", english: "relative"),
        Flashcard(pinyin: "jiélùn", chinese: "结论", russian: "вывод", english: "conclusion"),
        Flashcard(pinyin: "shānghài", chinese: "伤害", russian: "повреждать", english: "hurt"),
        Flashcard(pinyin: "bǐ pǔtōng rén bù yīyàng", chinese: "比普通人不一样", russian: "не такой, как обычные люди", english: "different from ordinary people"),
        Flashcard(pinyin: "gēn pǔtōng rén bù yīyàng", chinese: "跟普通人不一样", russian: "не такой, как обычные люди", english: "not the same as ordinary people"),
        Flashcard(pinyin: "juédìng", chinese: "决定", russian: "решать", english: "decide"),
        Flashcard(pinyin: "shì zhōngxīn", chinese: "市中心", russian: "центр города", english: "city center"),
        Flashcard(pinyin: "réngōng zhìnéng", chinese: "人工智能", russian: "искусственный интеллект", english: "AI"),
        Flashcard(pinyin: "gōngsī", chinese: "公司", russian: "компания", english: "company"),
        Flashcard(pinyin: "shēnghuó lùchéng", chinese: "生活路程", russian: "жизненный путь", english: "life journey"),
        Flashcard(pinyin: "lǚyóu", chinese: "旅游", russian: "путешествовать", english: "travel"),
        Flashcard(pinyin: "nàge shíhòu wǒ kāishǐ xué zhōngwén", chinese: "那个时候我开始学中文", russian: "тогда я начал учить китайский", english: "at that time I started learning Chinese"),
        Flashcard(pinyin: "wǒ kāishǐ xué zhōngwén de shíhòu", chinese: "我开始学中文的时候", russian: "когда я начал учить китайский", english: "when I started learning Chinese"),
        Flashcard(pinyin: "yǒuxiào", chinese: "有效", russian: "эффективный", english: "effective"),
        Flashcard(pinyin: "zhōngjí de shuǐpíng", chinese: "中级的水平", russian: "средний уровень", english: "intermediate level"),
        Flashcard(pinyin: "luójí", chinese: "逻辑", russian: "логика", english: "logic"),
        Flashcard(pinyin: "lìzi", chinese: "例子", russian: "пример", english: "example"),
        Flashcard(pinyin: "yīntiān", chinese: "阴天", russian: "облачное небо", english: "cloudy sky"),
        Flashcard(pinyin: "qíngtiān", chinese: "晴天", russian: "чистое небо", english: "clear sky"),
        Flashcard(pinyin: "gānjìng", chinese: "干净", russian: "чистый", english: "clean"),
        Flashcard(pinyin: "shāokǎo", chinese: "烧烤", russian: "барбекью", english: "barbecue")
    ]
}
