struct Lesson31Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "zuò yīdiǎnr de biānchéng", chinese: "做一点儿的编程", russian: "делать немного программирования", english: "do a little programming"),
        Flashcard(pinyin: "wǒ shìshì zuò app", chinese: "我试试做 app", russian: "я попробую создать приложение", english: "I'll try to make an app"),
        Flashcard(pinyin: "biān app", chinese: "编 app", russian: "писать приложение", english: "write an app"),
        Flashcard(pinyin: "fābù", chinese: "发布", russian: "постить", english: "post"),
        Flashcard(pinyin: "huā le bàn nián de shíjiān", chinese: "花了半年的时间", russian: "потратил полгода", english: "spent half a year"),
        Flashcard(pinyin: "biǎodá zìjǐ de sīxiǎng", chinese: "表达自己的思想", russian: "выражать собственные мысли", english: "express own thoughts"),
        Flashcard(pinyin: "liú cún", chinese: "保存", russian: "сохранять", english: "save"),
        Flashcard(pinyin: "fāzhǎn", chinese: "发展", russian: "прогресс", english: "progress"),
        Flashcard(pinyin: "zhǎngjìn", chinese: "进步", russian: "развитие", english: "development"),
        Flashcard(pinyin: "wǒ zài biānchéng yòu fāzhǎn", chinese: "我在编程又发展", russian: "я снова развиваюсь в программировании", english: "I am progressing in programming again"),
        Flashcard(pinyin: "yīqǐ zhù", chinese: "一起住", russian: "жить вместе", english: "live together"),
        Flashcard(pinyin: "shòu zài", chinese: "受在", russian: "пострадать от чего-то", english: "suffer from something"),
        Flashcard(pinyin: "jiéguǒ", chinese: "结果", russian: "результат", english: "result"),
        Flashcard(pinyin: "gēngxīn", chinese: "更新", russian: "обновить", english: "update"),
        Flashcard(pinyin: "wéifǎ de cāozuò", chinese: "违法的操作", russian: "нелегальная операция", english: "illegal operation"),
        Flashcard(pinyin: "xīnwén", chinese: "新闻", russian: "новости", english: "news"),
        Flashcard(pinyin: "guójì rén", chinese: "国际人", russian: "интернациональный человек", english: "international person"),
        Flashcard(pinyin: "guójí", chinese: "国籍", russian: "гражданство", english: "nationality"),
        Flashcard(pinyin: "luòsānjī", chinese: "洛杉矶", russian: "Лос-Анджелес", english: "Los Angeles"),
        Flashcard(pinyin: "tā zhù zài LA bànnián", chinese: "他住在 LA 半年", russian: "он живет в Лос-Анджелесе полгода", english: "he lives in LA for half a year"),
        Flashcard(pinyin: "jiàngdī", chinese: "降低", russian: "понижаться", english: "decrease"),
        Flashcard(pinyin: "jìqiǎo", chinese: "技巧", russian: "навык, техника", english: "skill, technique"),
        Flashcard(pinyin: "nénglì", chinese: "能力", russian: "способность, умение", english: "ability"),
        Flashcard(pinyin: "zhù zài", chinese: "住在", russian: "жить в", english: "live in"),
        Flashcard(pinyin: "shēng zài", chinese: "生在", russian: "родиться в", english: "be born in"),
        Flashcard(pinyin: "tíng zài", chinese: "停在", russian: "остановиться в", english: "stop at"),
        Flashcard(pinyin: "zuò zài", chinese: "坐在", russian: "сидеть в", english: "sit in"),
        Flashcard(pinyin: "shōurù", chinese: "收入", russian: "доход/заработок", english: "income/earnings"),
        Flashcard(pinyin: "gōnglǐ měi xiǎoshí", chinese: "公里每小时", russian: "км/час", english: "km/h"),
        Flashcard(pinyin: "chāochē", chinese: "超车", russian: "обгонять машину", english: "overtake car"),
        Flashcard(pinyin: "sàichē", chinese: "赛车", russian: "гонка", english: "race"),
        Flashcard(pinyin: "wēixiǎn", chinese: "危险", russian: "опасный", english: "dangerous"),
        Flashcard(pinyin: "ānquán", chinese: "安全", russian: "безопасный", english: "safe"),
        Flashcard(pinyin: "jiàshǐ", chinese: "驾驶", russian: "водить", english: "drive"),
        Flashcard(pinyin: "tícái", chinese: "题材", russian: "литературный жанр", english: "literary genre"),
        Flashcard(pinyin: "jìshù", chinese: "技术", russian: "технологии", english: "technology")
    ]
}
