struct Lesson25Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "zhè běn shū wǒ kàn le yí bàn", chinese: "这本书我看了一半", russian: "я прочитал половину этой книги", english: "I read half of this book"),
        Flashcard(pinyin: "gōngzuò rì/qī", chinese: "工作日/期", russian: "рабочий день", english: "working day"),
        Flashcard(pinyin: "jiérì de dì yī tiān", chinese: "节日的第一天", russian: "первый день праздника", english: "first day of the holiday"),
        Flashcard(pinyin: "zhuàngtài", chinese: "状态", russian: "состояние", english: "state"),
        Flashcard(pinyin: "qīzhōng zhùyì lì", chinese: "期中注意力", russian: "сфокусироваться", english: "focus"),
        Flashcard(pinyin: "zhìshǎo", chinese: "至少", russian: "по крайней мере/at least", english: "at least"),
        Flashcard(pinyin: "wǒ zhīshǎo xūyào liǎng nián de shíjiān lái xué", chinese: "我至少需要两年的时间来学", russian: "мне нужно по крайней мере два года, чтобы учиться", english: "I need at least two years to learn"),
        Flashcard(pinyin: "biànchéng", chinese: "变成", russian: "становиться", english: "become"),
        Flashcard(pinyin: "wǒ duì shū yǒu/gǎn xìngqù", chinese: "我对书有/感兴趣", russian: "я интересуюсь книгами", english: "I am interested in books"),
        Flashcard(pinyin: "wàimào", chinese: "外貌", russian: "внешность", english: "appearance"),
        Flashcard(pinyin: "yī mào chūn rén", chinese: "依貌取人", russian: "выбирать по внешности", english: "judge by appearance"),
        Flashcard(pinyin: "chéngxù yuán", chinese: "程序员", russian: "программист", english: "programmer"),
        Flashcard(pinyin: "zài dàxué xuéxí le bàn nián", chinese: "在大学学习了半年", russian: "учился в университете полгода", english: "studied at university for half a year"),
        Flashcard(pinyin: "yōudiǎn", chinese: "优点", russian: "преимущества", english: "advantages"),
        Flashcard(pinyin: "quēdiǎn", chinese: "缺点", russian: "недостатки", english: "disadvantages"),
        Flashcard(pinyin: "guò le jiérì", chinese: "过了节日", russian: "праздник прошел", english: "the holiday is over"),
        Flashcard(pinyin: "guò wán le jiérì", chinese: "过完了节日", russian: "праздник закончился", english: "the holiday is finished"),
        Flashcard(pinyin: "bǎochí", chinese: "保持", russian: "поддерживать", english: "maintain"),
        Flashcard(pinyin: "zhòngyào", chinese: "重要", russian: "важный", english: "important"),
        Flashcard(pinyin: "lùchéng", chinese: "路程", russian: "дорога/путь", english: "journey"),
        Flashcard(pinyin: "màoxiǎn", chinese: "冒险", russian: "рисковать/идти на риск", english: "take a risk"),
        Flashcard(pinyin: "nǐ ràng nǐ de shēnghuó gèng yǒuyìsi", chinese: "你让你的生活更有意思", russian: "сделай свою жизнь более интересной", english: "make your life more interesting"),
        Flashcard(pinyin: "sàibō pèngkè", chinese: "赛博朋克", russian: "киберпанк", english: "cyberpunk"),
        Flashcard(pinyin: "rénwù", chinese: "人物", russian: "персонаж", english: "character"),
        Flashcard(pinyin: "jìn yīdiǎnr", chinese: "近一点儿", russian: "поближе", english: "closer"),
        Flashcard(pinyin: "jiālǐ fù nǐ yà", chinese: "加利福尼亚", russian: "Калифорния", english: "California"),
        Flashcard(pinyin: "jīnglì", chinese: "精力", russian: "энергия", english: "energy"),
        Flashcard(pinyin: "zhōngxué", chinese: "中学", russian: "средняя школа", english: "middle school"),
        Flashcard(pinyin: "fēnshù", chinese: "分数", russian: "оценка", english: "score"),
        Flashcard(pinyin: "chéngjī", chinese: "成绩", russian: "оценки/результат", english: "grades"),
        Flashcard(pinyin: "cóng 6 dào 10 suì", chinese: "从6到10岁", russian: "с 6 до 10 лет", english: "from 6 to 10 years old"),
        Flashcard(pinyin: "jiāo le xīn de péngyǒu", chinese: "交了新的朋友", russian: "завел новых друзей", english: "made new friends"),
        Flashcard(pinyin: "16 suì qián", chinese: "16岁前", russian: "до 16 лет", english: "before 16 years old"),
        Flashcard(pinyin: "wǒ 16 suì qián zài kànle shū", chinese: "我16岁前在看了书", russian: "я читал книги до 16 лет", english: "I read books before I was 16")
    ]
}
