struct Lesson29Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "wǒ de lùshàng yào 40 fēnzhōng", chinese: "我的路上要40分钟", russian: "мой путь занимает 40 минут", english: "my commute takes 40 minutes"),
        Flashcard(pinyin: "yī ge bàn xiǎoshí", chinese: "一个半小时", russian: "полтора часа", english: "one and a half hours"),
        Flashcard(pinyin: "chéngxù", chinese: "程序", russian: "программа", english: "program"),
        Flashcard(pinyin: "wǎngluò fèi", chinese: "网络费", russian: "плата за интернет", english: "internet fee"),
        Flashcard(pinyin: "gōngzuò rì", chinese: "工作日", russian: "рабочий день", english: "workday"),
        Flashcard(pinyin: "xūnǐ zhuānyòng wǎng", chinese: "虚拟专用网", russian: "VPN", english: "VPN"),
        Flashcard(pinyin: "mùdì", chinese: "目的", russian: "цель", english: "goal"),
        Flashcard(pinyin: "mùbiāo", chinese: "目标", russian: "цель", english: "target"),
        Flashcard(pinyin: "xīnqíng", chinese: "心情", russian: "настроение", english: "mood"),
        Flashcard(pinyin: "B bǐ G gēn jiǔ", chinese: "B比G更久", russian: "B дольше G", english: "B longer than G"),
        Flashcard(pinyin: "kānglái nóngcūn", chinese: "康来农村", russian: "приходит из деревни", english: "comes from the village"),
        Flashcard(pinyin: "gēn nóngcūn yīyàng", chinese: "跟农村一样", russian: "как и деревня", english: "same as the village"),
        Flashcard(pinyin: "dān bǎn huáxuě", chinese: "单板滑雪", russian: "сноуборд", english: "snowboarding"),
        Flashcard(pinyin: "lù shìpín/pāi", chinese: "录视频/拍", russian: "снимать видео", english: "record video"),
        Flashcard(pinyin: "zì pái gān/bàng", chinese: "自拍杆/棒", russian: "селфи палка", english: "selfie stick"),
        Flashcard(pinyin: "zhuānyè de shèxiàngjī", chinese: "专业的摄像机", russian: "проф видеокамера", english: "professional video camera"),
        Flashcard(pinyin: "pāi zì pái", chinese: "拍自拍", russian: "делать селфи", english: "take selfies"),
        Flashcard(pinyin: "kǒngbù", chinese: "恐怖", russian: "страшный", english: "scary"),
        Flashcard(pinyin: "guàiwù", chinese: "怪物", russian: "монстр", english: "monster"),
        Flashcard(pinyin: "jiāngshī", chinese: "僵尸", russian: "зомби", english: "zombie"),
        Flashcard(pinyin: "xǔxuè guǐ", chinese: "吸血鬼", russian: "вампир", english: "vampire"),
        Flashcard(pinyin: "wūpó", chinese: "巫婆", russian: "ведьма", english: "witch"),
        Flashcard(pinyin: "guò", chinese: "过", russian: "проводить (праздник)", english: "celebrate (holiday)"),
        Flashcard(pinyin: "wǔfàn", chinese: "午饭", russian: "обед", english: "lunch"),
        Flashcard(pinyin: "shuì yīhuǐr", chinese: "睡一会儿", russian: "поспать немножко", english: "take a nap"),
        Flashcard(pinyin: "huàzhuāng", chinese: "化妆", russian: "макияж", english: "makeup"),
        Flashcard(pinyin: "zìyóu zhíyè zhě", chinese: "自由职业者", russian: "фриланс", english: "freelancer"),
        Flashcard(pinyin: "jīběn", chinese: "基本", russian: "базовый", english: "basic"),
        Flashcard(pinyin: "jīdì", chinese: "基地", russian: "база", english: "base"),
        Flashcard(pinyin: "fābù", chinese: "发布", russian: "постить/публиковать", english: "post/publish"),
        Flashcard(pinyin: "yī jiā jiǔbā", chinese: "一家酒吧", russian: "один бар (семейное заведение)", english: "one bar (family business)"),
        Flashcard(pinyin: "wǒ xīngqī sān yǒu kèchéng", chinese: "我星期三有课程", russian: "у меня урок в среду", english: "I have a lesson on Wednesday"),
        Flashcard(pinyin: "zhuīpěng", chinese: "追捧", russian: "востребованный", english: "popular"),
        Flashcard(pinyin: "shuǐpíng dī/gāo", chinese: "水平低/高", russian: "низкий/высокий уровень", english: "low/high level"),
        Flashcard(pinyin: "shī le xīwàng", chinese: "失了希望", russian: "потерять надежду", english: "lose hope"),
        Flashcard(pinyin: "yīshēng", chinese: "一生", russian: "вся жизнь", english: "a lifetime"),
        Flashcard(pinyin: "lǎn/lǎnduò", chinese: "懒/懒惰", russian: "ленивый", english: "lazy"),
        Flashcard(pinyin: "zhuàngtài", chinese: "状态", russian: "состояние", english: "state"),
        Flashcard(pinyin: "zhì yù", chinese: "治愈", russian: "вылечить", english: "cure"),
        Flashcard(pinyin: "zài xīfāng", chinese: "在西方", russian: "на западе", english: "in the West"),
        Flashcard(pinyin: "xíguàn", chinese: "习惯", russian: "привычка/привыкать", english: "habit/get used to")
    ]
}
