struct Lesson10Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Bà fān zuò wán", chinese: "把饭做完", russian: "Закончить готовить еду", english: "Finish cooking the meal"),
        Flashcard(pinyin: "Zuò wán fàn", chinese: "做完饭", russian: "Приготовить еду", english: "Prepare the meal"),
        Flashcard(pinyin: "Bà gōngzuò yòng zài tāmen shēngyì", chinese: "把工作用在他们生意", russian: "Использовать работу в их бизнесе", english: "Use the work in their business"),
        Flashcard(pinyin: "Gěi wǒ jiàn miàn", chinese: "给我见面", russian: "Встретиться со мной", english: "Meet with me"),
        Flashcard(pinyin: "Gěi wǒ sòng lǐwù", chinese: "给我送礼物", russian: "Дать мне подарок", english: "Give me a gift"),
        Flashcard(pinyin: "Dǎ diànhuà gěi wǒ", chinese: "打电话给我", russian: "Позвонить мне", english: "Call me"),
        Flashcard(pinyin: "Duì māma zuò fàn", chinese: "对妈妈做饭", russian: "Готовить для мамы", english: "Cook for mom"),
        Flashcard(pinyin: "Yàoqǐng jiā cì", chinese: "邀请加次", russian: "Пригласить еще раз", english: "Invite again"),
        Flashcard(pinyin: "Jiàn le xīn rén de miàn", chinese: "见了新人的面", russian: "Встретил нового человека", english: "Met a new person"),
        Flashcard(pinyin: "Qù lè yī gè pǐsà cāntīng", chinese: "去了一个披萨餐厅", russian: "Посетил пиццерию", english: "Visited a pizza restaurant"),
        Flashcard(pinyin: "Zài lái yī cì", chinese: "再来一次", russian: "Сделать это еще раз", english: "Do it again"),
        Flashcard(pinyin: "Tā míngtiān huì zài lái", chinese: "他明天会再来", russian: "Он придет завтра снова", english: "He will come again tomorrow"),
        Flashcard(pinyin: "Hùxiāng rènshi", chinese: "互相认识", russian: "Знать друг друга", english: "Know each other"),
        Flashcard(pinyin: "Wéishénme tā gēn qítā/biéde nánrén tiāowǔ", chinese: "为什么她跟其他/别的男人跳舞", russian: "Почему она танцует с другими мужчинами", english: "Why she dances with other men"),
        Flashcard(pinyin: "Xī fāng kēxué", chinese: "西方科学", russian: "Западная наука", english: "Western science"),
        Flashcard(pinyin: "Zěnme shēng", chinese: "怎么声", russian: "Как звучит", english: "How does it sound"),
        Flashcard(pinyin: "Xiàng fǎ", chinese: "想法", russian: "Мысль", english: "Idea"),
        Flashcard(pinyin: "Gòu wù", chinese: "购物", russian: "Шоппинг", english: "Shopping"),
        Flashcard(pinyin: "Guàng jiē", chinese: "逛街", russian: "Прогуливаться по магазинам", english: "Window shopping"),
        Flashcard(pinyin: "Yì shù qū", chinese: "艺术区", russian: "Арт-дистрикт", english: "Art district"),
        Flashcard(pinyin: "Zài nǎr wǒ juédé hěn shūfú", chinese: "在那儿我觉得很舒服", russian: "Там мне комфортно", english: "I feel comfortable there"),
        Flashcard(pinyin: "Fàng yīnyuè", chinese: "放音乐", russian: "Слушать музыку", english: "Play music"),
        Flashcard(pinyin: "Tā jiéshù wánr de shíhòu", chinese: "他结束玩儿的时候", russian: "Когда он закончил играть", english: "When he finished playing"),
        Flashcard(pinyin: "Wǒ qí mótuōchē qù nàge dìfāng", chinese: "我骑摩托车去那个地方", russian: "Я поехал на мотоцикле в то место", english: "I rode a motorcycle to that place"),
        Flashcard(pinyin: "Làngfèi shíjiān", chinese: "浪费时间", russian: "Тратить время впустую", english: "Waste time"),
        Flashcard(pinyin: "Yǒuqí", chinese: "尤其", russian: "Особенно", english: "Especially"),
        Flashcard(pinyin: "Cánjiā yīxiē huódòng", chinese: "参加一些活动", russian: "Принять участие в некоторых мероприятиях", english: "Participate in some activities"),
        Flashcard(pinyin: "Zhōngshì", chinese: "中式", russian: "Китайский стиль", english: "Chinese style"),
        Flashcard(pinyin: "Ānpái", chinese: "安排", russian: "Планировать", english: "Plan"),
        Flashcard(pinyin: "Sài chē", chinese: "赛车", russian: "Гонки", english: "Racing"),
        Flashcard(pinyin: "Zhǎng shì", chinese: "涨势", russian: "Рост", english: "Increase"),
        Flashcard(pinyin: "Kàn hǎo", chinese: "看好", russian: "Полагаться", english: "Rely on"),
        Flashcard(pinyin: "Kàn jiàn", chinese: "看见", russian: "Увидеть", english: "See"),
        Flashcard(pinyin: "Kàn dào", chinese: "看到", russian: "Заметить", english: "Notice"),
        Flashcard(pinyin: "Liúxíng", chinese: "流行", russian: "Популярный", english: "Popular"),
        Flashcard(pinyin: "Guānyú", chinese: "关于", russian: "О (чем-то)", english: "About"),
        Flashcard(pinyin: "Zhí dào hěn duō dōngxī", chinese: "知道很多东西", russian: "Знать много вещей", english: "Know a lot of things"),
        Flashcard(pinyin: "Kēxué", chinese: "科学", russian: "Наука", english: "Science"),
        Flashcard(pinyin: "Wǒmen tiānyáng shì zěnme shēng de", chinese: "我们太阳是怎么生的", russian: "Как родилось наше солнце", english: "How our sun was born"),
        Flashcard(pinyin: "Néng liàng", chinese: "能量", russian: "Энергия", english: "Energy"),
        Flashcard(pinyin: "Lílùn", chinese: "理论", russian: "Теория", english: "Theory"),
        Flashcard(pinyin: "Wǔlǐ", chinese: "物理", russian: "Физика", english: "Physics"),
        Flashcard(pinyin: "Xīnxī", chinese: "信息", russian: "Информация", english: "Information"),
        Flashcard(pinyin: "Zhíwù", chinese: "植物", russian: "Растения", english: "Plants"),
        Flashcard(pinyin: "Shēngwù", chinese: "生物", russian: "Живой организм", english: "Living organism"),
        Flashcard(pinyin: "Zài nàn", chinese: "灾难", russian: "Катастрофа", english: "Disaster"),
        Flashcard(pinyin: "Shì huò", chinese: "事故", russian: "Дорожное происшествие", english: "Accident"),
        Flashcard(pinyin: "Xī fāng", chinese: "西方", russian: "Западная", english: "Western"),
        Flashcard(pinyin: "Shēngměng", chinese: "生猛", russian: "Животная сила", english: "Vigorous"),
        Flashcard(pinyin: "Zěnme shēng", chinese: "怎么生", russian: "Как родился", english: "How it was born"),
        Flashcard(pinyin: "Zhè ge bèizi shì wǒ huài de", chinese: "这个杯子是我坏的", russian: "Эта кружка испорчена мной", english: "This cup is spoiled by me")
    ]
}
