struct Lesson6Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Wǒ hé péngyǒu jiànmiàn le", chinese: "我和朋友见面了", russian: "Я встретился с другом", english: "I met with a friend"),
        Flashcard(pinyin: "Xiànzài tā qù wǒ de jiā", chinese: "现在他去我的家", russian: "Теперь он идет к моему дому", english: "Now he is going to my house"),
        Flashcard(pinyin: "Dǎgōng", chinese: "打工", russian: "Подработка", english: "Part-time job"),
        Flashcard(pinyin: "Dǎgōng lí wǒ jiā bù yuǎn", chinese: "打工离我家不远", russian: "Подработка не далеко от моего дома", english: "Part-time job is not far from my home"),
        Flashcard(pinyin: "Shāngdiàn", chinese: "商店", russian: "Магазин", english: "Store"),
        Flashcard(pinyin: "Huǒchē zhàn", chinese: "火车站", russian: "Вокзал", english: "Train station"),
        Flashcard(pinyin: "Chāoshì lí huǒchē zhàn zǒulù 20 fēnzhōng", chinese: "超市离火车站走路20分钟", russian: "Супермаркет в 20 минутах ходьбы от вокзала", english: "The supermarket is a 20-minute walk from the train station"),
        Flashcard(pinyin: "Jiàqī", chinese: "假期", russian: "Отпуск", english: "Vacation"),
        Flashcard(pinyin: "Bù yào gěi wǒ jiàqī", chinese: "不要给我假期", russian: "Не нужно мне отпуска", english: "Don't give me a vacation"),
        Flashcard(pinyin: "Kāishǐ gōngzuò", chinese: "开始工作", russian: "Начать работать", english: "Start working"),
        Flashcard(pinyin: "Tóngyì le", chinese: "同意了", russian: "Согласен", english: "Agreed"),
        Flashcard(pinyin: "Wǎngshàng/xianshàng zhùcè", chinese: "网上/线上注册", russian: "Зарегистрироваться онлайн", english: "Register online"),
        Flashcard(pinyin: "Wénjiàn", chinese: "文件", russian: "Документы", english: "Documents"),
        Flashcard(pinyin: "Bàn qiānzhèng", chinese: "办签证", russian: "Оформлять визу", english: "Get a visa"),
        Flashcard(pinyin: "Bàn hé tóng", chinese: "办合同", russian: "Оформлять контракт", english: "Get a contract"),
        Flashcard(pinyin: "Fàng jià", chinese: "放假", russian: "Отдыхать дома", english: "Take a holiday"),
        Flashcard(pinyin: "Jiérì", chinese: "节日", russian: "Праздник", english: "Holiday"),
        Flashcard(pinyin: "Zhōumò", chinese: "周末", russian: "Выходные", english: "Weekend"),
        Flashcard(pinyin: "Lǎodòng jié", chinese: "劳动节", russian: "День труда", english: "Labor Day"),
        Flashcard(pinyin: "Yáncháng", chinese: "延长", russian: "Продлевать", english: "Extend"),
        Flashcard(pinyin: "Yǒng qítā de fāngshì", chinese: "用其他的方式", russian: "Использовать другие методы", english: "Use other methods"),
        Flashcard(pinyin: "Dìfāng", chinese: "地方", russian: "Место", english: "Place"),
        Flashcard(pinyin: "Dōngxī", chinese: "东西", russian: "Вещи", english: "Things"),
        Flashcard(pinyin: "Bànfǎ", chinese: "办法", russian: "Метод", english: "Method"),
        Flashcard(pinyin: "Gěi wǒ mǎi kāfēi zài xīngbākè", chinese: "给我买咖啡在星巴克", russian: "Купи мне кофе в Starbucks", english: "Buy me coffee at Starbucks"),
        Flashcard(pinyin: "Zhuàn qián", chinese: "赚钱", russian: "Зарабатывать деньги", english: "Make money"),
        Flashcard(pinyin: "Yǒudiǎn er tiáopí", chinese: "有点儿调皮", russian: "Немного непоседа", english: "A little naughty"),
        Flashcard(pinyin: "Tínghuà yīdiǎn er", chinese: "听话一点儿", russian: "Будь послушным", english: "Be a little obedient"),
        Flashcard(pinyin: "Bìngqiě", chinese: "并且", russian: "К тому же", english: "Moreover"),
        Flashcard(pinyin: "Jiǎnxiāo", chinese: "减小", russian: "Уменьшать", english: "Reduce"),
        Flashcard(pinyin: "Shíjiān", chinese: "时间", russian: "Время", english: "Time"),
        Flashcard(pinyin: "Qiántiān", chinese: "前天", russian: "Позавчера", english: "The day before yesterday"),
        Flashcard(pinyin: "Hòutiān", chinese: "后天", russian: "Послезавтра", english: "The day after tomorrow"),
        Flashcard(pinyin: "Liáotiān yī xiē", chinese: "聊天一些", russian: "Немножко поболтать", english: "Chat a little"),
        Flashcard(pinyin: "Ràng", chinese: "让", russian: "Заставлять", english: "Let/Make"),
        Flashcard(pinyin: "Yǔnxǔ", chinese: "允许", russian: "Разрешать/позволять", english: "Allow/Permit"),
        Flashcard(pinyin: "Wèi hūn", chinese: "未婚", russian: "Не женат/не замужем", english: "Unmarried"),
        Flashcard(pinyin: "Shēnghuó fāngshì", chinese: "生活方式", russian: "Образ жизни", english: "Lifestyle"),
        Flashcard(pinyin: "Bù néng zài yīqǐ", chinese: "不能在一起", russian: "Не могут быть вместе", english: "Cannot be together"),
        Flashcard(pinyin: "Zhèngfǔ", chinese: "政府", russian: "Правительство", english: "Government"),
        Flashcard(pinyin: "Gēn zhèngfǔ yǒuguān", chinese: "跟政府有关", russian: "Имеет отношение к правительству", english: "Related to the government"),
        Flashcard(pinyin: "Líhūn", chinese: "离婚", russian: "Развод", english: "Divorce"),
        Flashcard(pinyin: "Diūshī", chinese: "丢失", russian: "Потерять/лишиться", english: "Lose"),
        Flashcard(pinyin: "Xuǎnzé", chinese: "选择", russian: "Выбирать", english: "Choose"),
        Flashcard(pinyin: "Méi yǒu tā gāo", chinese: "没有他高", russian: "Не такой высокий как он", english: "Not as tall as him"),
        Flashcard(pinyin: "Wǒ bǐ tā cōngmíng", chinese: "我比他聪明", russian: "Я умнее него", english: "I am smarter than him"),
        Flashcard(pinyin: "Alābó péngyǒu", chinese: "阿拉伯朋友", russian: "Арабский друг", english: "Arab friend"),
        Flashcard(pinyin: "Yǒudiǎn er nánguò", chinese: "有点儿难过", russian: "Немного грустно", english: "A little sad")
    ]
}
