struct Lesson30Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "17 000 yí wàn qī", chinese: "17 000 一万七", russian: "семнадцать тысяч", english: "seventeen thousand"),
        Flashcard(pinyin: "jiàgé bǐjiào gāo/dī", chinese: "价格比较高/低", russian: "цена выше/ниже", english: "price higher/lower"),
        Flashcard(pinyin: "bǎocún", chinese: "保存", russian: "сохранить", english: "save"),
        Flashcard(pinyin: "fàng zhàopiàn dào chéngxù", chinese: "放照片到程序", russian: "добавить фото в программу", english: "add photo to the program"),
        Flashcard(pinyin: "péixùn kèchéng", chinese: "培训课程", russian: "обучающие уроки", english: "training courses"),
        Flashcard(pinyin: "YouTube dào", chinese: "YouTube道", russian: "ютуб канал", english: "YouTube channel"),
        Flashcard(pinyin: "píngguǒ shāngdiàn", chinese: "苹果商店", russian: "эппл стор", english: "Apple store"),
        Flashcard(pinyin: "jīngyàn", chinese: "经验", russian: "опыт", english: "experience"),
        Flashcard(pinyin: "shíshì zuò", chinese: "实事做", russian: "делать", english: "do"),
        Flashcard(pinyin: "fùzhì", chinese: "复制", russian: "копировать", english: "copy"),
        Flashcard(pinyin: "chéngxù dàimǎ", chinese: "程序代码", russian: "код программирования", english: "program code"),
        Flashcard(pinyin: "zhìliàng", chinese: "质量", russian: "качество", english: "quality"),
        Flashcard(pinyin: "zàn", chinese: "赞", russian: "лайк", english: "like"),
        Flashcard(pinyin: "diǎn zàn", chinese: "点赞", russian: "поставить лайк", english: "give a like"),
        Flashcard(pinyin: "zhùyì/xiǎngfǎ", chinese: "主意/想法", russian: "идея", english: "idea"),
        Flashcard(pinyin: "Swift biānyì yǔyán", chinese: "Swift 编译语言", russian: "язык программирования Swift", english: "Swift programming language"),
        Flashcard(pinyin: "gǔgē", chinese: "谷歌", russian: "гугл", english: "Google"),
        Flashcard(pinyin: "xīnqíng", chinese: "心情", russian: "настроение", english: "mood"),
        Flashcard(pinyin: "méi jiàn tā", chinese: "没见她", russian: "не встречал ее", english: "didn't meet her"),
        Flashcard(pinyin: "míngnián", chinese: "明年", russian: "следующий год", english: "next year"),
        Flashcard(pinyin: "jìshù", chinese: "技术", russian: "технология", english: "technology"),
        Flashcard(pinyin: "juédìng", chinese: "决定", russian: "решать/решение", english: "decide/decision"),
        Flashcard(pinyin: "diànlǎn", chinese: "电缆", russian: "кабель", english: "cable"),
        Flashcard(pinyin: "fāzhǎn", chinese: "发展", russian: "развиваться", english: "develop"),
        Flashcard(pinyin: "fāzhǎn de hěn kuài", chinese: "发展得很快", russian: "развиваться быстро", english: "develop very fast"),
        Flashcard(pinyin: "gānzào de qìhòu", chinese: "干燥的气候", russian: "сухой климат", english: "dry climate"),
        Flashcard(pinyin: "gānzào", chinese: "干燥", russian: "сухой/засушливый", english: "dry"),
        Flashcard(pinyin: "líng xià liǎng dù", chinese: "零下两度", russian: "минус два градуса", english: "minus two degrees"),
        Flashcard(pinyin: "fāngbiàn", chinese: "方便", russian: "удобно", english: "convenient"),
        Flashcard(pinyin: "tǎolùn", chinese: "讨论", russian: "обсуждать", english: "discuss"),
        Flashcard(pinyin: "liǎng gè duō yuè", chinese: "两个多月", russian: "больше двух месяцев", english: "more than two months"),
        Flashcard(pinyin: "11 duō ge rén", chinese: "11多个 人", russian: "более 11 человек", english: "more than 11 people"),
        Flashcard(pinyin: "zhīshi", chinese: "知识", russian: "знания", english: "knowledge"),
        Flashcard(pinyin: "rìjì", chinese: "日记", russian: "дневник", english: "diary"),
        Flashcard(pinyin: "chúle ... yǐwài", chinese: "除了 ... 以外", russian: "кроме ...", english: "besides ..."),
        Flashcard(pinyin: "chúle yīxiē tiān wǒ měitiān dōu xuéxí le", chinese: "除了一些天我每天都学习了", russian: "кроме нескольких дней, я учился каждый день", english: "except for a few days, I studied every day"),
        Flashcard(pinyin: "gēn zhōngguó rén shuōhuà", chinese: "跟中国人说话", russian: "говорить с китайцами", english: "speak with Chinese people")
    ]
}
