struct Lesson5Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Ānpái", chinese: "安排", russian: "Планировать/план", english: "Plan/Arrange"),
        Flashcard(pinyin: "Hǎojiǔ bùjiàn", chinese: "好久不见", russian: "Давно не виделись", english: "Long time no see"),
        Flashcard(pinyin: "Méi jiàn miàn", chinese: "没见面", russian: "Не виделись", english: "Haven't met"),
        Flashcard(pinyin: "Wǒ de lǎopó yě qù", chinese: "我的老婆也去", russian: "Моя жена тоже идет", english: "My wife is also going"),
        Flashcard(pinyin: "Nǚxìng péngyǒu", chinese: "女性朋友", russian: "Девушка-друг", english: "Female friend"),
        Flashcard(pinyin: "Nǚ péngyǒu", chinese: "女朋友", russian: "Девушка", english: "Girlfriend"),
        Flashcard(pinyin: "Wǒ kànjiàn le wǒ de péngyǒu", chinese: "我看见了我的朋友", russian: "Я увидел своего друга", english: "I saw my friend"),
        Flashcard(pinyin: "Yī gè jiu bā", chinese: "一个酒吧", russian: "Один бар", english: "A bar"),
        Flashcard(pinyin: "Hé zuì", chinese: "喝醉", russian: "Пьяный", english: "Drunk"),
        Flashcard(pinyin: "Hé tóng dàoqí le", chinese: "合同到期了", russian: "Контракт истек", english: "Contract expired"),
        Flashcard(pinyin: "Huò...huò...", chinese: "或...或...", russian: "Или...или...", english: "Either...or..."),
        Flashcard(pinyin: "Hái shì", chinese: "还是", russian: "Или (выбор имеет значение)", english: "Or (choice matters)"),
        Flashcard(pinyin: "Huò zhě", chinese: "或者", russian: "Или (не имеет значения)", english: "Or (doesn't matter)"),
        Flashcard(pinyin: "Xiǎozhǎng", chinese: "校长", russian: "Директор школы", english: "Principal"),
        Flashcard(pinyin: "Tǎolùn shēngyì", chinese: "讨论生意", russian: "Обсуждать бизнес", english: "Discuss business"),
        Flashcard(pinyin: "Zhège dōngxī zuò de hěn hǎo", chinese: "这个东西做得很好", russian: "Эта вещь сделана хорошо", english: "This thing is well made"),
        Flashcard(pinyin: "Yāoqiú", chinese: "要求", russian: "Требовать/требование", english: "Demand/Request"),
        Flashcard(pinyin: "Tiáojiàn", chinese: "条件", russian: "Условия", english: "Conditions"),
        Flashcard(pinyin: "Wǒmen gēn fānyì zhě tǎolùn le tiáojiàn", chinese: "我们跟翻译者讨论了条件", russian: "Мы обсудили условия с переводчиком", english: "We discussed the terms with the translator"),
        Flashcard(pinyin: "Wǒ de yāoqiú shì jiā gōngzī", chinese: "我的要求是加工资", russian: "Мое требование - повышение зарплаты", english: "My request is a raise"),
        Flashcard(pinyin: "Dāi zài jiā", chinese: "呆在家", russian: "Оставаться дома", english: "Stay at home"),
        Flashcard(pinyin: "Liú xià", chinese: "留下", russian: "Оставаться", english: "Stay"),
        Flashcard(pinyin: "Shěng qián", chinese: "省钱", russian: "Копить деньги", english: "Save money"),
        Flashcard(pinyin: "Wǒ gēn péngyǒu jiànmiàn", chinese: "我跟朋友见面", russian: "Я встретился с другом", english: "I met with a friend"),
        Flashcard(pinyin: "Dōngxī", chinese: "东西", russian: "Вещи", english: "Things"),
        Flashcard(pinyin: "Yánchí", chinese: "延迟", russian: "Задержка", english: "Delay"),
        Flashcard(pinyin: "Yǐqián/ Zǎo yīdiǎn er", chinese: "以前/早一点儿", russian: "Ранее/чуть раньше", english: "Before/a little earlier"),
        Flashcard(pinyin: "Guānyú", chinese: "关于", russian: "О (чем-то)", english: "About"),
        Flashcard(pinyin: "Jiànyì", chinese: "建议", russian: "Совет", english: "Advice"),
        Flashcard(pinyin: "Wǒ yào guānyú jiàoyù liáotiān", chinese: "我要关于教育聊天", russian: "Я хочу поговорить об образовании", english: "I want to chat about education"),
        Flashcard(pinyin: "Liú", chinese: "留", russian: "Оставаться", english: "Stay"),
        Flashcard(pinyin: "Guójì", chinese: "国际", russian: "Международный", english: "International"),
        Flashcard(pinyin: "Huánjìng", chinese: "环境", russian: "Окружающая среда", english: "Environment"),
        Flashcard(pinyin: "Jiàoyù", chinese: "教育", russian: "Образование", english: "Education")
    ]
}
