struct Lesson16Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "lèyuán", chinese: "乐园", russian: "парк развлечений", english: "amusement park"),
        Flashcard(pinyin: "fēngbào", chinese: "风暴", russian: "ураган/шторм", english: "storm"),
        Flashcard(pinyin: "qūyù", chinese: "故域", russian: "район/дистрикт", english: "district"),
        Flashcard(pinyin: "liǎng tiān", chinese: "两天", russian: "продолжительность после глагола", english: "two days"),
        Flashcard(pinyin: "shēngcí", chinese: "生词", russian: "новые слова", english: "new words"),
        Flashcard(pinyin: "yīnpín", chinese: "音频", russian: "аудиоподкаст", english: "audio podcast"),
        Flashcard(pinyin: "jiànyì", chinese: "建议", russian: "совет", english: "advice"),
        Flashcard(pinyin: "yǒuyòng de dōngxī", chinese: "有用的东西", russian: "полезные вещи", english: "useful things"),
        Flashcard(pinyin: "zhǔnbèi zǎofàn", chinese: "准备早饭", russian: "готовить завтрак", english: "prepare breakfast"),
        Flashcard(pinyin: "zuò zǎofàn", chinese: "做早饭", russian: "делать завтрак", english: "make breakfast"),
        Flashcard(pinyin: "yī zhōu sān cì", chinese: "一周三次", russian: "три раза в неделю", english: "three times a week"),
        Flashcard(pinyin: "zǒngzhī", chinese: "总之", russian: "в общем", english: "in general"),
        Flashcard(pinyin: "zìjǐ", chinese: "自己", russian: "сам", english: "oneself"),
        Flashcard(pinyin: "zhīchí", chinese: "支持", russian: "поддерживать", english: "support"),
        Flashcard(pinyin: "bǎochí", chinese: "保持", russian: "поддерживать (что то)", english: "maintain"),
        Flashcard(pinyin: "yǐngxiǎng", chinese: "影响", russian: "влиять", english: "influence"),
        Flashcard(pinyin: "ràng", chinese: "让", russian: "позволять", english: "let"),
        Flashcard(pinyin: "juédìng", chinese: "决定", russian: "решение", english: "decision"),
        Flashcard(pinyin: "kāishǐ", chinese: "开始", russian: "начинать", english: "begin"),
        Flashcard(pinyin: "xīnqíng", chinese: "心情", russian: "настроение", english: "mood"),
        Flashcard(pinyin: "kùnnán", chinese: "困难", russian: "трудности", english: "difficulties"),
        Flashcard(pinyin: "kèfú kùnnán", chinese: "克服困难", russian: "преодолевать трудности", english: "overcome difficulties"),
        Flashcard(pinyin: "lìqi", chinese: "力气", russian: "энергия/силы", english: "strength"),
        Flashcard(pinyin: "shìjiè", chinese: "世界", russian: "мир", english: "world"),
        Flashcard(pinyin: "zhège shìjiè shàng", chinese: "这个世界上", russian: "на этом свете", english: "in this world"),
        Flashcard(pinyin: "chǔxù", chinese: "储蓄", russian: "сбережения", english: "savings"),
        Flashcard(pinyin: "yǒu diǎn er", chinese: "有点儿", russian: "немного", english: "a little"),
        Flashcard(pinyin: "bànfǎ", chinese: "办法", russian: "метод", english: "method"),
        Flashcard(pinyin: "xiǎng le xiǎng", chinese: "想了想", russian: "подумать", english: "think"),
        Flashcard(pinyin: "zhěng tiān", chinese: "整天", russian: "весь день", english: "all day"),
        Flashcard(pinyin: "gēngzhèng", chinese: "更正", russian: "исправлять", english: "correct")
    ]
}
