struct Lesson35Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "zàntíng", chinese: "暂停", russian: "приостанавливаться (временно)", english: "pause (temporarily)"),
        Flashcard(pinyin: "huódòng", chinese: "活动", russian: "активити/церемония", english: "activity/ceremony"),
        Flashcard(pinyin: "zhǔchírén", chinese: "主持人", russian: "ведущий", english: "host"),
        Flashcard(pinyin: "yǎnshuō", chinese: "演说", russian: "речь", english: "speech"),
        Flashcard(pinyin: "lǎngdú", chinese: "朗读", russian: "читать вслух", english: "read aloud"),
        Flashcard(pinyin: "yāoqǐng", chinese: "邀请", russian: "приглашать", english: "invite"),
        Flashcard(pinyin: "nánfēi", chinese: "南非", russian: "Южная Африка", english: "South Africa"),
        Flashcard(pinyin: "fēizhōu", chinese: "非洲", russian: "Африка (континент)", english: "Africa (continent)"),
        Flashcard(pinyin: "wǒ gēn tā shuō huà", chinese: "我跟他说话", russian: "я разговариваю с ним", english: "I talk to him"),
        Flashcard(pinyin: "fùyù", chinese: "富裕", russian: "богатый", english: "rich"),
        Flashcard(pinyin: "tā bù shì cóng fùyù de jiātíng", chinese: "他不是从富裕的家庭", russian: "он не из богатой семьи", english: "he is not from a rich family"),
        Flashcard(pinyin: "tā bǐ wǒ niánqīng", chinese: "他比我年轻", russian: "он моложе меня", english: "he is younger than me"),
        Flashcard(pinyin: "qiāng", chinese: "枪", russian: "оружие", english: "gun"),
        Flashcard(pinyin: "shǒudū", chinese: "首都", russian: "столица", english: "capital"),
        Flashcard(pinyin: "měi gè yuē dàgài 30 gè rén bèi shā", chinese: "每个约大概30个人被杀", russian: "каждый около 30 человек убит", english: "about 30 people were killed"),
        Flashcard(pinyin: "ānquán", chinese: "安全", russian: "безопасно", english: "safe"),
        Flashcard(pinyin: "wēixiǎn", chinese: "危险", russian: "опасно", english: "dangerous"),
        Flashcard(pinyin: "xiōngshā", chinese: "凶杀", russian: "убийство/убивать", english: "murder/to kill"),
        Flashcard(pinyin: "tóurù", chinese: "投入", russian: "вкладывать", english: "invest"),
        Flashcard(pinyin: "jīnróng shìchǎng", chinese: "金融市场", russian: "финансовый рынок", english: "financial market"),
        Flashcard(pinyin: "zhōngjiū", chinese: "终究", russian: "в конце концов", english: "eventually"),
        Flashcard(pinyin: "diū", chinese: "丢", russian: "терять", english: "lose"),
        Flashcard(pinyin: "cóng kāishǐ qǐ bù", chinese: "从开始起步", russian: "начинать с начала", english: "start from the beginning"),
        Flashcard(pinyin: "shòuhòu jīnglǐ", chinese: "售后经理", russian: "менеджер по продажам", english: "sales manager"),
        Flashcard(pinyin: "rénmen dàduō xiǎoqì", chinese: "人们大多小气", russian: "люди в большинстве случаев жадные", english: "people are mostly stingy"),
        Flashcard(pinyin: "cèlüè", chinese: "策略", russian: "стратегия", english: "strategy"),
        Flashcard(pinyin: "jīngyàn", chinese: "经验", russian: "опыт", english: "experience"),
        Flashcard(pinyin: "bù tài jīngcháng jiànmiàn", chinese: "不太经常见面", russian: "не часто видимся", english: "not meet often"),
        Flashcard(pinyin: "chǔxù", chinese: "储蓄", russian: "сбережения", english: "savings"),
        Flashcard(pinyin: "zhù zài běijīng zhōngxīn", chinese: "住在北京中心", russian: "жить в центре Пекина", english: "live in the center of Beijing"),
        Flashcard(pinyin: "gǎn shíjiān", chinese: "赶时间", russian: "торопиться", english: "hurry"),
        Flashcard(pinyin: "déchū jiélùn", chinese: "得出结论", russian: "делать выводы", english: "draw conclusions"),
        Flashcard(pinyin: "zài dì yī gè jiǔbā", chinese: "在第一个酒吧", russian: "в первом баре", english: "at the first bar"),
        Flashcard(pinyin: "jítā shǒu", chinese: "吉他手", russian: "гитарист", english: "guitarist"),
        Flashcard(pinyin: "biǎoyǎn", chinese: "表演", russian: "выступать", english: "perform"),
        Flashcard(pinyin: "yáogǔn lèduì", chinese: "摇滚乐队", russian: "рок группа", english: "rock band"),
        Flashcard(pinyin: "tā zài lèduì zhōng", chinese: "他在乐队中", russian: "он состоит в группе", english: "he is in the band"),
        Flashcard(pinyin: "shēngyīn hěn dà", chinese: "声音很大", russian: "очень громко", english: "very loud"),
        Flashcard(pinyin: "hěn shíshàng", chinese: "很时尚", russian: "очень модный", english: "very fashionable"),
        Flashcard(pinyin: "wǒ liǎng diǎn jiéshù le", chinese: "我两点结束了", russian: "я закончил в два часа", english: "I finished at 2 o'clock"),
        Flashcard(pinyin: "huí jiā", chinese: "回家", russian: "вернуться домой", english: "go home"),
        Flashcard(pinyin: "yè zǒng huì/jué lè bù", chinese: "夜总会/俱乐部", russian: "ночной клуб", english: "night club"),
    ]
}
