struct Lesson7Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Zhè nián", chinese: "这年", russian: "Этот год", english: "This year"),
        Flashcard(pinyin: "Yī tiān", chinese: "一天", russian: "Один день", english: "One day"),
        Flashcard(pinyin: "Zhège yuè", chinese: "这个月", russian: "Этот месяц", english: "This month"),
        Flashcard(pinyin: "Míngnián", chinese: "明年", russian: "Следующий год", english: "Next year"),
        Flashcard(pinyin: "Qùnián", chinese: "去年", russian: "Прошлый год", english: "Last year"),
        Flashcard(pinyin: "Xuéxí le yīdiǎn er de zhōngwén", chinese: "学习了一点儿的中文", russian: "Выучил немного китайского", english: "Learned a little Chinese"),
        Flashcard(pinyin: "Rén gōng zhì néng", chinese: "人工智能", russian: "Искусственный интеллект", english: "Artificial intelligence"),
        Flashcard(pinyin: "Hěn liúxíng = hěn hóng", chinese: "很流行 = 很红", russian: "Очень популярный", english: "Very popular"),
        Flashcard(pinyin: "Míng chēng", chinese: "名称", russian: "Название", english: "Name"),
        Flashcard(pinyin: "Kèchéng", chinese: "课程", russian: "Урок", english: "Course"),
        Flashcard(pinyin: "Liǎng nián qián", chinese: "两年前", russian: "Два года назад", english: "Two years ago"),
        Flashcard(pinyin: "Bàn nián hòu", chinese: "半年后", russian: "Через полгода", english: "In half a year"),
        Flashcard(pinyin: "Wǔ miáo de shíjiān", chinese: "五秒的时间", russian: "Пять секунд времени", english: "Five seconds of time"),
        Flashcard(pinyin: "Jīdì", chinese: "基地", russian: "База", english: "Base"),
        Flashcard(pinyin: "Gāosù", chinese: "高速", russian: "Высокая скорость", english: "High speed"),
        Flashcard(pinyin: "Shēngcí", chinese: "生词", russian: "Новое слово", english: "New word"),
        Flashcard(pinyin: "Jùzi", chinese: "句子", russian: "Предложение", english: "Sentence"),
        Flashcard(pinyin: "Chéngsè", chinese: "橙色", russian: "Оранжевый цвет", english: "Orange color"),
        Flashcard(pinyin: "Chéngzi", chinese: "橙子", russian: "Апельсин", english: "Orange"),
        Flashcard(pinyin: "Júzi", chinese: "桔子", russian: "Мандарин", english: "Tangerine"),
        Flashcard(pinyin: "Yāogun yuè", chinese: "摇滚乐", russian: "Рок-музыка", english: "Rock music"),
        Flashcard(pinyin: "Wàngjì le", chinese: "忘记了", russian: "Забыл", english: "Forgot"),
        Flashcard(pinyin: "Bù jìde", chinese: "不记得", russian: "Не помнить", english: "Don't remember"),
        Flashcard(pinyin: "Wǒ jué dìng", chinese: "我决定", russian: "Я решил", english: "I decided"),
        Flashcard(pinyin: "Yàncháng", chinese: "延长", russian: "Продлевать", english: "Extend"),
        Flashcard(pinyin: "Huā shíjiān", chinese: "花时间", russian: "Тратить время", english: "Spend time"),
        Flashcard(pinyin: "Hùkǒu", chinese: "户口", russian: "Прописка", english: "Household registration"),
        Flashcard(pinyin: "Yuányīn", chinese: "原因", russian: "Причина", english: "Reason"),
        Flashcard(pinyin: "Huódòng", chinese: "活动", russian: "Мероприятие", english: "Activity"),
        Flashcard(pinyin: "Lǎn", chinese: "懒", russian: "Ленивый", english: "Lazy"),
        Flashcard(pinyin: "Kàn shìpín", chinese: "看视频", russian: "Смотреть видео", english: "Watch videos"),
        Flashcard(pinyin: "Shāngdiàn", chinese: "商店", russian: "Магазин", english: "Store"),
        Flashcard(pinyin: "Gòuwù", chinese: "购物", russian: "Шоппинг", english: "Shopping"),
        Flashcard(pinyin: "Guàngjiē", chinese: "逛街", russian: "Прогуливаться по магазинам", english: "Window shopping"),
        Flashcard(pinyin: "Yìshù qū", chinese: "艺术区", russian: "Арт-дистрикт", english: "Art district"),
        Flashcard(pinyin: "Zài nǎr wǒ juéde hěn shūfú", chinese: "在那儿我觉得很舒服", russian: "Там мне комфортно", english: "I feel comfortable there"),
        Flashcard(pinyin: "Fàng yīnyuè", chinese: "放音乐", russian: "Слушать музыку", english: "Play music"),
        Flashcard(pinyin: "Tā jiéshù wánr de shíhòu", chinese: "他结束玩儿的时候", russian: "Когда он закончил играть", english: "When he finished playing"),
        Flashcard(pinyin: "Wǒ qí mótuōchē qù nàge dìfāng", chinese: "我骑摩托车去那个地方", russian: "Я поехал на мотоцикле в то место", english: "I rode a motorcycle to that place"),
        Flashcard(pinyin: "Làngfèi shíjiān", chinese: "浪费时间", russian: "Тратить время впустую", english: "Waste time"),
        Flashcard(pinyin: "Yǒuqí", chinese: "尤其", russian: "Особенно", english: "Especially")
    ]
}
