struct Lesson14Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "xuéxí shēngcí", chinese: "学习生词", russian: "учить новые слова", english: "learn new words"),
        Flashcard(pinyin: "hěn shǎo", chinese: "很少", russian: "редко", english: "rarely"),
        Flashcard(pinyin: "qián zhōu", chinese: "前周", russian: "прошлая неделя", english: "last week"),
        Flashcard(pinyin: "duǒcáng", chinese: "躲藏", russian: "прятаться", english: "hide"),
        Flashcard(pinyin: "zhè zhōu liǎng cì lái", chinese: "这周两次来", russian: "приходить дважды в неделю", english: "come twice this week"),
        Flashcard(pinyin: "lái liǎng cì", chinese: "来两次", russian: "приходить дважды", english: "come twice"),
        Flashcard(pinyin: "ānquán", chinese: "安全", russian: "безопасность", english: "safety"),
        Flashcard(pinyin: "fēizhōu rén", chinese: "非洲人", russian: "африканец", english: "African"),
        Flashcard(pinyin: "chuānghu", chinese: "窗户", russian: "окно", english: "window"),
        Flashcard(pinyin: "chúfáng", chinese: "厨房", russian: "кухня", english: "kitchen"),
        Flashcard(pinyin: "pá", chinese: "爬", russian: "взбираться", english: "climb"),
        Flashcard(pinyin: "qiáng", chinese: "墙", russian: "стена", english: "wall"),
        Flashcard(pinyin: "xiāofáng duìyuán", chinese: "消防队员", russian: "пожарник", english: "firefighter"),
        Flashcard(pinyin: "jiàoyù", chinese: "教育", russian: "образование", english: "education"),
        Flashcard(pinyin: "jǐnzhāng", chinese: "紧张", russian: "волноваться", english: "nervous"),
        Flashcard(pinyin: "bǐjiào ānquán", chinese: "比较安全", russian: "относительно безопасный", english: "relatively safe"),
        Flashcard(pinyin: "quēdiǎn", chinese: "缺点", russian: "недостаток", english: "disadvantage"),
        Flashcard(pinyin: "lǜshī", chinese: "律师", russian: "юрист", english: "lawyer"),
        Flashcard(pinyin: "cónglái bù...", chinese: "从来不...", russian: "никогда", english: "never"),
        Flashcard(pinyin: "mǔyǔ", chinese: "母语", russian: "родной язык", english: "mother tongue"),
        Flashcard(pinyin: "yīkào", chinese: "依靠", russian: "зависеть от", english: "depend on"),
        Flashcard(pinyin: "yáncháng qiānzhèng", chinese: "延长签证", russian: "продливать визу", english: "extend visa"),
        Flashcard(pinyin: "dàoqī", chinese: "到期", russian: "заканчивается (срок)", english: "expire"),
        Flashcard(pinyin: "pínghéng", chinese: "平衡", russian: "баланс/равновесие", english: "balance"),
        Flashcard(pinyin: "dádào pínghéng", chinese: "达到平衡", russian: "достигать баланса", english: "achieve balance"),
        Flashcard(pinyin: "zhǎng dà", chinese: "长大", russian: "расти", english: "grow up"),
        Flashcard(pinyin: "zhōuwéi", chinese: "周围", russian: "окружение", english: "environment"),
        Flashcard(pinyin: "xuǎnzé", chinese: "选择", russian: "выбор", english: "choice"),
        Flashcard(pinyin: "shānghài", chinese: "伤害", russian: "вредить", english: "harm"),
        Flashcard(pinyin: "màoxiǎn", chinese: "冒险", russian: "рисковать", english: "take risks"),
        Flashcard(pinyin: "bǐjiào", chinese: "比较", russian: "относительно", english: "relatively"),
        Flashcard(pinyin: "zài YouTube xuéxí le", chinese: "在YouTube学习了", russian: "учился на YouTube", english: "learned on YouTube"),
        Flashcard(pinyin: "dào", chinese: "到", russian: "канал", english: "channel"),
        Flashcard(pinyin: "qízhōng zhùyì lì", chinese: "其中注意力", russian: "фокусироваться внимание", english: "focus attention"),
        Flashcard(pinyin: "cānjiā dàxué", chinese: "参加大学", russian: "посещать университет", english: "attend university"),
        Flashcard(pinyin: "diànyǐng", chinese: "电影", russian: "фильм", english: "movie"),
        Flashcard(pinyin: "diànshìjù", chinese: "电视剧", russian: "телесериал", english: "TV series"),
        Flashcard(pinyin: "bù xuéxí le", chinese: "不学习了", russian: "не учиться", english: "not study"),
        Flashcard(pinyin: "méi xuéxí", chinese: "没学习", russian: "не учился", english: "did not study"),
        Flashcard(pinyin: "xīnqíng", chinese: "心情", russian: "настроение", english: "mood"),
        Flashcard(pinyin: "zhǐ zǎoshang yǒu shíjiān", chinese: "只早上有时间", russian: "время только утром", english: "only have time in the morning"),
        Flashcard(pinyin: "bù chūxué de shuǐpíng", chinese: "不初学的水平", russian: "не начальный уровень", english: "not beginner level"),
        Flashcard(pinyin: "hànzì", chinese: "汉字", russian: "иероглиф", english: "Chinese character"),
        Flashcard(pinyin: "zìmǔ", chinese: "字母", russian: "буквы", english: "letters")
    ]
}
