struct Lesson15Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "yālì", chinese: "压力", russian: "стресс", english: "stress"),
        Flashcard(pinyin: "dàilái yālì", chinese: "带来压力", russian: "приносит стресс", english: "bring stress"),
        Flashcard(pinyin: "duō yī gè xiǎoshí", chinese: "多一个小时", russian: "на час больше", english: "one more hour"),
        Flashcard(pinyin: "dǎzhé", chinese: "打折", russian: "скидка", english: "discount"),
        Flashcard(pinyin: "hěn dà de dǎzhé", chinese: "很大的打折", russian: "большая скидка", english: "big discount"),
        Flashcard(pinyin: "bǎifēn zhī 70", chinese: "百分之七十", russian: "70%", english: "70 percent"),
        Flashcard(pinyin: "lí wǒ jiā yào zǒulù 3 gōnglǐ", chinese: "离我家要走路三公里", russian: "от моего дома 3 км пешком", english: "3 kilometers from my home"),
        Flashcard(pinyin: "zhù zài zhōngguó de qíjiān duì nǐ dàilái le shénme", chinese: "住在中国的期间对你带来了什么", russian: "что принесло тебе проживание в Китае", english: "what has living in China brought to you"),
        Flashcard(pinyin: "jiārén de shēnghuó", chinese: "家人的生活", russian: "жизнь семьи", english: "family life"),
        Flashcard(pinyin: "zhōngděng rén", chinese: "中等人", russian: "средний класс", english: "middle class"),
        Flashcard(pinyin: "zhèngfǔ", chinese: "政府", russian: "правительство", english: "government"),
        Flashcard(pinyin: "bǎohù", chinese: "保护", russian: "охранять", english: "protect"),
        Flashcard(pinyin: "shěng qián", chinese: "省钱", russian: "копить деньги", english: "save money"),
        Flashcard(pinyin: "tóurù qián", chinese: "投入钱", russian: "инвестировать", english: "invest money"),
        Flashcard(pinyin: "tóuzī qián", chinese: "投资钱", russian: "инвестировать", english: "invest money"),
        Flashcard(pinyin: "shēnghuó shuǐpíng", chinese: "生活水平", russian: "уровень жизни", english: "living standard"),
        Flashcard(pinyin: "dāngrán", chinese: "当然", russian: "конечно", english: "of course"),
        Flashcard(pinyin: "guānyú wǒ", chinese: "关于我", russian: "обо мне", english: "about me"),
        Flashcard(pinyin: "duō 10 bèi", chinese: "多十倍", russian: "в 10 раз больше", english: "10 times more"),
        Flashcard(pinyin: "yōudiǎn", chinese: "优点", russian: "преимущество", english: "advantage"),
        Flashcard(pinyin: "dī", chinese: "低", russian: "низкий", english: "low"),
        Flashcard(pinyin: "zhùguo", chinese: "住过", russian: "жил", english: "lived"),
        Flashcard(pinyin: "zhùguo zài dà de chéngshì", chinese: "住过在大的城市", russian: "жил в большом городе", english: "lived in a big city"),
        Flashcard(pinyin: "Duōlúnduō", chinese: "多伦多", russian: "Торонто", english: "Toronto"),
        Flashcard(pinyin: "zhù zài zhōngguó", chinese: "住在中国", russian: "жить в Китае", english: "live in China"),
        Flashcard(pinyin: "èr wéi mǎ", chinese: "二维码", russian: "QR код", english: "QR code"),
        Flashcard(pinyin: "sǎo èr wéi mǎ", chinese: "扫一扫二维码", russian: "сканировать QR код", english: "scan QR code"),
        Flashcard(pinyin: "làngfèi", chinese: "浪费", russian: "тратить впустую", english: "waste"),
        Flashcard(pinyin: "nà zhǒng màoyì", chinese: "那种贸易", russian: "такая торговля", english: "such trade"),
        Flashcard(pinyin: "jīngyàn", chinese: "经验", russian: "опыт", english: "experience"),
        Flashcard(pinyin: "zhè zhǒng hángyè", chinese: "这种行业", russian: "эта отрасль", english: "this industry"),
        Flashcard(pinyin: "chūchāi", chinese: "出差", russian: "ехать в командировку", english: "business trip"),
        Flashcard(pinyin: "gòuwù", chinese: "购物", russian: "покупать", english: "shop"),
        Flashcard(pinyin: "zhíyè", chinese: "职业", russian: "профессия", english: "profession"),
        Flashcard(pinyin: "wǎngyè", chinese: "网页", russian: "страница вебсайта", english: "webpage"),
        Flashcard(pinyin: "yóuxiāng", chinese: "邮箱", russian: "почта", english: "mail"),
        Flashcard(pinyin: "shèjì", chinese: "设计", russian: "дизайн", english: "design")
    ]
}
