struct Lesson3Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "Yīqǐ zhùzài", chinese: "一起住在", russian: "Жить вместе", english: "Live together"),
        Flashcard(pinyin: "Zhè zhōu", chinese: "这周", russian: "Эта неделя", english: "This week"),
        Flashcard(pinyin: "Yèyíng", chinese: "野营", russian: "Кемпинг", english: "Camping"),
        Flashcard(pinyin: "Zhù zài yīqǐ", chinese: "住在一起", russian: "Жить вместе", english: "Live together"),
        Flashcard(pinyin: "Yī gè bàn xiǎoshí", chinese: "一个半小时", russian: "Полтора часа", english: "One and a half hours"),
        Flashcard(pinyin: "Zuò dìtiě", chinese: "坐地铁", russian: "Ехать на метро", english: "Take the subway"),
        Flashcard(pinyin: "Qùguò měiguó", chinese: "去过美国", russian: "Был в Америке", english: "Have been to America"),
        Flashcard(pinyin: "Bàn gè xiǎoshí", chinese: "半个小时", russian: "Полчаса", english: "Half an hour"),
        Flashcard(pinyin: "Qùle měiguó", chinese: "去了美国", russian: "Поехал в Америку", english: "Went to America"),
        Flashcard(pinyin: "Qùguò mòxīgē", chinese: "去过墨西哥", russian: "Посетил Мексику", english: "Have been to Mexico"),
        Flashcard(pinyin: "Qùguòle gōngyuán", chinese: "去过了公园", russian: "Посетил парк", english: "Have been to the park"),
        Flashcard(pinyin: "Tiān'é", chinese: "天鹅", russian: "Лебедь", english: "Swan"),
        Flashcard(pinyin: "Nǐ chīguò mángguǒ ma?", chinese: "你吃过芒果吗?", russian: "Ты ел манго?", english: "Have you eaten mango?"),
        Flashcard(pinyin: "Zìrán / dà zìrán", chinese: "自然 / 大自然", russian: "Природа", english: "Nature"),
        Flashcard(pinyin: "Xiàbān de shíhòu", chinese: "下班的时候", russian: "Когда закончилась работа", english: "When work is over"),
        Flashcard(pinyin: "Xiàbān yǐhòu", chinese: "下班以后", russian: "После окончания работы", english: "After work"),
        Flashcard(pinyin: "Huā", chinese: "花", russian: "Тратить", english: "Spend"),
        Flashcard(pinyin: "Wǒ xiànzài zhèngzài chīfàn", chinese: "我现在正在吃饭", russian: "Я сейчас ем", english: "I am eating now"),
        Flashcard(pinyin: "Wǒ huāle yī gè bàn xiǎoshí de shíjiān", chinese: "我花了一个半小时的时间", russian: "Я потратил полтора часа", english: "I spent one and a half hours"),
        Flashcard(pinyin: "Nuówēi", chinese: "挪威", russian: "Норвегия", english: "Norway"),
        Flashcard(pinyin: "Qùguòle", chinese: "去过了", russian: "Посетил", english: "Have been to"),
        Flashcard(pinyin: "Diū", chinese: "丢", russian: "Потерять", english: "Lose"),
        Flashcard(pinyin: "Xià gè yuè", chinese: "下个月", russian: "Следующий месяц", english: "Next month"),
        Flashcard(pinyin: "Yī gè yuè qián", chinese: "一个月前", russian: "Месяц назад", english: "A month ago"),
        Flashcard(pinyin: "Míngnián", chinese: "明年", russian: "Следующий год", english: "Next year"),
        Flashcard(pinyin: "Qùnián", chinese: "去年", russian: "Прошлый год", english: "Last year"),
        Flashcard(pinyin: "Wǒ jiànmiànle yī gè wūkèlán de péngyǒu", chinese: "我见面了一个乌克兰的朋友", russian: "Я встретил украинского друга", english: "I met a Ukrainian friend"),
        Flashcard(pinyin: "Liáotiān", chinese: "聊天", russian: "Болтать", english: "Chat"),
        Flashcard(pinyin: "Wǒ gēn yī gè péngyǒu jiànmiàn", chinese: "我跟一个朋友见面", russian: "Я встретил друга", english: "I met with a friend"),
        Flashcard(pinyin: "Guānxì", chinese: "关系", russian: "Отношения", english: "Relationship"),
        Flashcard(pinyin: "Hěn zhuānyè", chinese: "很专业", russian: "Очень профессиональный", english: "Very professional"),
        Flashcard(pinyin: "Gēqǔ", chinese: "歌曲", russian: "Песня", english: "Song"),
        Flashcard(pinyin: "Néng", chinese: "能", russian: "Мочь", english: "Can"),
        Flashcard(pinyin: "Kěyǐ", chinese: "可以", russian: "Можно", english: "May"),
        Flashcard(pinyin: "Huài", chinese: "坏", russian: "Плохой", english: "Bad"),
        Flashcard(pinyin: "Yǒu diǎn er huài le", chinese: "有点儿坏了", russian: "Немного испорчен", english: "A little bad"),
        Flashcard(pinyin: "Qín xián", chinese: "琴弦", russian: "Струна", english: "String"),
        Flashcard(pinyin: "Yī zhōu yī cì", chinese: "一周一次", russian: "Раз в неделю", english: "Once a week"),
        Flashcard(pinyin: "94 gōngjīn", chinese: "94 公斤", russian: "94 кг", english: "94 kg"),
        Flashcard(pinyin: "Yǒu diǎn er pàng", chinese: "有点儿胖", russian: "Немного толстый", english: "A little fat"),
        Flashcard(pinyin: "Jiǎnféi", chinese: "减肥", russian: "Похудеть", english: "Lose weight"),
        Flashcard(pinyin: "Zài zhōngjiān", chinese: "在中间", russian: "В середине", english: "In the middle"),
        Flashcard(pinyin: "Jiānguǒ", chinese: "坚果", russian: "Орехи", english: "Nuts"),
        Flashcard(pinyin: "Hétáo", chinese: "核桃", russian: "Грецкий орех", english: "Walnut"),
        Flashcard(pinyin: "Bādàmǔ", chinese: "巴达木", russian: "Миндаль", english: "Almond"),
        Flashcard(pinyin: "Zhēnguǒ", chinese: "榛果", russian: "Фундук", english: "Hazelnut"),
        Flashcard(pinyin: "Yāoguǒ", chinese: "腰果", russian: "Кешью", english: "Cashew"),
        Flashcard(pinyin: "Wǒ kàn qǐlái yǒudiǎn er shòu", chinese: "我看起来有点儿瘦", russian: "Я выгляжу немного худым", english: "I look a little thin"),
        Flashcard(pinyin: "Hěn yǒu yìsi duì yújiā", chinese: "很有意思对瑜伽", russian: "Очень интересуюсь йогой", english: "Very interested in yoga"),
        Flashcard(pinyin: "Wǒ bù shì hěn è le", chinese: "我不是很饿了", russian: "Я не очень голоден", english: "I am not very hungry"),
        Flashcard(pinyin: "Duì yújiā hěn gǎn xìngqù", chinese: "对瑜伽很感兴趣", russian: "Очень интересуюсь йогой", english: "Very interested in yoga"),
        Flashcard(pinyin: "Duì wǒ yǒu yǐngxiǎng", chinese: "对我有影响", russian: "Влияет на меня", english: "Influences me"),
        Flashcard(pinyin: "Shòu", chinese: "瘦", russian: "Худой", english: "Thin"),
        Flashcard(pinyin: "Shòule yī xiē", chinese: "瘦了一些", russian: "Немного похудел", english: "Lost some weight"),
        Flashcard(pinyin: "Jiēshòu", chinese: "接受", russian: "Принимать", english: "Accept"),
        Flashcard(pinyin: "Shíyàn", chinese: "实验", russian: "Эксперимент", english: "Experiment"),
        Flashcard(pinyin: "Zuìdī de zhòngliàng shì 70 gōngjīn", chinese: "最低的重量是70公斤", russian: "Минимальный вес 70 кг", english: "The minimum weight is 70 kg"),
        Flashcard(pinyin: "Míngxiǎng", chinese: "冥想", russian: "Медитировать", english: "Meditate"),
        Flashcard(pinyin: "Mófǎng", chinese: "模仿", russian: "Подражать", english: "Imitate")
    ]
}
