struct Lesson26Flashcards {
    static let data: [Flashcard] = [
        Flashcard(pinyin: "xīnqíng", chinese: "心情", russian: "настроение", english: "mood"),
        Flashcard(pinyin: "qún", chinese: "群", russian: "группа", english: "group"),
        Flashcard(pinyin: "wēixìn qún", chinese: "微信群", russian: "группа в WeChat", english: "WeChat group"),
        Flashcard(pinyin: "chuàngzào", chinese: "创造", russian: "создавать", english: "create"),
        Flashcard(pinyin: "lādìng měizhōu", chinese: "拉丁美洲", russian: "Латинская Америка", english: "Latin America"),
        Flashcard(pinyin: "yāoqǐng", chinese: "邀请", russian: "приглашать", english: "invite"),
        Flashcard(pinyin: "jiāoliú", chinese: "交流", russian: "общение", english: "communication"),
        Flashcard(pinyin: "jiāo péngyǒu", chinese: "交朋友", russian: "заводить друзей", english: "make friends"),
        Flashcard(pinyin: "wǒmen hùxiāng bù rènshi", chinese: "我们互相不认识", russian: "мы не знаем друг друга", english: "we don't know each other"),
        Flashcard(pinyin: "zài cì", chinese: "再一次", russian: "еще раз", english: "again"),
        Flashcard(pinyin: "shān diào", chinese: "删掉", russian: "удалять", english: "delete"),
        Flashcard(pinyin: "wūshī", chinese: "巫师", russian: "шаман", english: "shaman"),
        Flashcard(pinyin: "yídìng rén", chinese: "一定人", russian: "индеец", english: "native American"),
        Flashcard(pinyin: "zhīshì", chinese: "知识", russian: "знания", english: "knowledge"),
        Flashcard(pinyin: "xīfāng de sīxiǎng", chinese: "西方的思想", russian: "западное мышление", english: "western thinking"),
        Flashcard(pinyin: "kōngjiān", chinese: "空间", russian: "пространство", english: "space"),
        Flashcard(pinyin: "liánxì fāngshì", chinese: "联系方式", russian: "контакт", english: "contact method"),
        Flashcard(pinyin: "fāxiàn", chinese: "发现", russian: "замечать", english: "notice"),
        Flashcard(pinyin: "kāichú/cítuì", chinese: "开除/辞退", russian: "увольнять", english: "fire"),
        Flashcard(pinyin: "pèifú", chinese: "佩服", russian: "восхищаться", english: "admire"),
        Flashcard(pinyin: "wèi mǒu rén gōngzuò", chinese: "为某人工作", russian: "работать на кого-то", english: "work for someone"),
        Flashcard(pinyin: "wǒmen yǒu hěn hǎo de shuōhuà", chinese: "我们有很好的说话", russian: "мы хорошо разговариваем", english: "we have good conversations"),
        Flashcard(pinyin: "wǒmen liáotiān de tǐng hǎo", chinese: "我们聊天的挺好", russian: "мы хорошо общаемся", english: "we chat well"),
        Flashcard(pinyin: "jíshǐ", chinese: "即使", russian: "даже если", english: "even if"),
        Flashcard(pinyin: "shìqíng", chinese: "事情", russian: "дело", english: "matter"),
        Flashcard(pinyin: "nǐ zěnmeyàng zuò gōngzuò?", chinese: "你怎么样做工作?", russian: "как ты работаешь?", english: "how do you work?"),
        Flashcard(pinyin: "nǐ zuò de gōngzuò zěnmeyàng?", chinese: "你做的工作怎么样?", russian: "как твоя работа?", english: "how is your work?"),
        Flashcard(pinyin: "kuài de xiě", chinese: "快地写", russian: "быстро писать", english: "write quickly"),
        Flashcard(pinyin: "wànshèngjié", chinese: "万圣节", russian: "Хеллоуин", english: "Halloween"),
        Flashcard(pinyin: "shèngdàn jié", chinese: "圣诞节", russian: "Рождество", english: "Christmas"),
        Flashcard(pinyin: "wèishēng jiān", chinese: "卫生间", russian: "туалет", english: "toilet"),
        Flashcard(pinyin: "wèishēng", chinese: "卫生", russian: "гигиена", english: "hygiene"),
        Flashcard(pinyin: "wèishìjī", chinese: "威士忌", russian: "виски", english: "whiskey"),
        Flashcard(pinyin: "guò jié", chinese: "过节", russian: "отмечать праздник", english: "celebrate holiday"),
        Flashcard(pinyin: "qùnián", chinese: "去年", russian: "прошлый год", english: "last year"),
        Flashcard(pinyin: "lǎo péngyǒu", chinese: "老朋友", russian: "старый друг", english: "old friend"),
        Flashcard(pinyin: "shuìjiào le hěn cháng shíjiān", chinese: "睡觉了很长时间", russian: "долго спать", english: "sleep for a long time"),
        Flashcard(pinyin: "kèchéng", chinese: "课程", russian: "урок", english: "lesson"),
        Flashcard(pinyin: "gōng'àn jú", chinese: "公安局", russian: "полицейский участок", english: "police station")
    ]
}
